jadx-core/src/main/java/jadx/core/dex/nodes/parser/DebugInfoParser.java
jadx-core/src/main/java/jadx/core/dex/visitors/SimplifyVisitor.java

Fix processing of debug info (if local variable used before declaring a debug info)
Corrections in SimplifyVisitor are made to bypass the test failures.

Fix processing of debug info

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/core/clsp/ClspGraph.java
jadx-core/src/main/java/jadx/core/utils/BlockUtils.java

Please refer to each commit log.

fixed a few bugs resulting program hang

---

jadx-core/src/main/java/jadx/api/ResourceFile.java
jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java
jadx-core/src/main/java/jadx/core/utils/android/AndroidResourcesUtils.java
jadx-core/src/main/java/jadx/core/utils/files/FileUtils.java
jadx-core/src/main/java/jadx/core/utils/files/InputFile.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java
jadx-gui/src/main/java/jadx/gui/treemodel/JRoot.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

support arsc raw file view

---

jadx-gui/src/main/java/jadx/gui/ui/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/SearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/UsageDialog.java
jadx-gui/src/main/java/jadx/gui/utils/Utils.java
jadx-gui/src/main/java/jadx/gui/utils/search/CodeIndex.java
jadx-gui/src/main/java/jadx/gui/utils/search/SearchIndex.java
jadx-gui/src/main/java/jadx/gui/utils/search/SimpleIndex.java
jadx-gui/src/main/java/jadx/gui/utils/search/StringRef.java
jadx-gui/src/main/java/jadx/gui/utils/search/TextSearchIndex.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties

This pull request contains two improvements for the search dialog:
1. Option added for case insensitive searching
2. Pagination added in case more than 100 results are found

Search dialog improvements

---

jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/core/codegen/CodeWriter.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/XmlDeobf.java

https://github.com/skylot/jadx/pull/288

Xml deobf 2.0

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java
jadx-core/src/main/java/jadx/core/utils/android/AndroidResourcesUtils.java

Hi, there are a few things:
- generated code isn't getting saved by some reason
- I believe it's not an issue that I don't create inner classes?
- I mentioned arrays in original R classes like ``` public static final int[] ZoomOval = new int[0]; ```, I will find out why they exist, and add it in a new commit in future
This PR is for https://github.com/skylot/jadx/issues/308

Generates code of missing R class

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java

Exports resources first

---

jadx-core/src/main/java/jadx/api/ResourceType.java
jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/core/xmlgen/ResContainer.java
jadx-core/src/main/java/jadx/core/xmlgen/ResourcesSaver.java

Saves all available resources #360

Saves all resources

---

jadx-core/src/main/java/jadx/core/dex/visitors/typeinference/TypeInference.java
jadx-core/src/test/java/jadx/tests/integration/arrays/TestArrays4.java

The problem is described via test case. I'm not sure if it does break smth else.

fix: return type lost after type inference

---

jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java
jadx-core/src/test/java/jadx/tests/integration/names/TestReservedClassNames.java
jadx-core/src/test/smali/names/TestReservedClassNames.smali

Fix class with reserved java keywords

---

build.gradle
jadx-cli/build.gradle

mockito to 2.25.1
spock to 1.3-groovy-2.5
jcommander to 1.75

Upgrade dependencies

---

jadx-core/src/test/java/jadx/NotYetImplemented.java
jadx-core/src/test/java/jadx/NotYetImplementedExtension.java

test: add NotYetImplemented feature

---

jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

update chinese simplified language

update chinese simplified language

---

jadx-core/src/test/java/jadx/tests/api/compiler/DynamicCompiler.java

test: warn about compiler not found, and gracefully report failure.

---

jadx-core/src/test/java/jadx/tests/api/compiler/StaticCompiler.java

Similar to #511, but with `StaticCompiler`

test: warn about compiler not found

---

jadx-core/src/main/java/jadx/core/codegen/TypeGen.java
jadx-core/src/test/java/jadx/tests/integration/arrays/TestRedundantType.java
jadx-core/src/test/java/jadx/tests/integration/types/TestTypeResolver4.java

fix: redundant byte and short cast (#538)

---

jadx-core/src/main/java/jadx/core/dex/visitors/SimplifyVisitor.java
jadx-core/src/test/java/jadx/tests/integration/arith/TestFieldIncrement2.java

I am not very comfortable with the code, because it can get easily messy, but it gives an idea of what should be done.
The fix is done by merging two `InsnNode`s to make one.

fix: field increment

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-cli/src/test/java/jadx/cli/RenameConverterTest.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/core/deobf/NameMapper.java
jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

feat: add options to configure "renaming" (#570)

---

jadx-core/src/main/java/jadx/core/dex/regions/conditions/IfCondition.java
jadx-core/src/main/java/jadx/core/dex/visitors/regions/IfMakerHelper.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestTernaryInIf.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestTernaryInIf2.java
jadx-core/src/test/smali/conditions/TestTernaryInIf2.smali

fix: conditions in ternary if (#449)

---

jadx-core/build.gradle
jadx-core/src/main/java/jadx/core/utils/files/InputFile.java
jadx-core/src/test/java/jadx/tests/api/SmaliTest.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

Fix #391 
Supported in command line and in GUI.

feat: support smali files (#391)

---

jadx-core/src/main/java/jadx/api/JavaClass.java
jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/utils/PathTypeAdapter.java

- Tree expansions, and expanding them back when the project is open.

feat(gui): save tree expansions in project

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/CodePanel.java
jadx-gui/src/main/java/jadx/gui/utils/TextStandardActions.java
jadx-gui/src/main/java/jadx/gui/utils/Utils.java

Issue https://github.com/skylot/jadx/issues/165

Implements command (CMD) button for MacOS

---

jadx-core/src/main/java/jadx/core/dex/regions/conditions/IfCondition.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions17.java

fix: bitwise or/and with non-boolean (#628)

---

jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/test/java/jadx/tests/integration/others/TestCastOfNull.java

 fix: null cast (#636)

---

README.md

Added macOS installation with brew documentation in README.md

Added macOS installation with brew documentation

---

build.gradle

fix: Workaround for IntelliJ bug on import line in build.gradle

---

jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/main/java/jadx/core/dex/nodes/ClassNode.java

Hopefully this the final fix for #848
@skalot I think I found a way to record all inlined classes. I am not sure if the way I have chosen is what you had in mind. Therefore consider this PR as a base for discussion.

Record inlined classes and also generate Smali code for them

---

jadx-gui/src/main/java/jadx/gui/treemodel/JField.java
jadx-gui/src/main/java/jadx/gui/treemodel/JMethod.java
jadx-gui/src/main/java/jadx/gui/treemodel/JNode.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java
jadx-gui/src/main/java/jadx/gui/utils/search/TextSearchIndex.java

As discussed in #882 the index based text search for methods and fields needed some improvement. 
Therefore for methods and fields I activated the description/code column to show and highlight was is actually been searched. 
Also the class search has been changed as it allowed to search for the full class name including package name but only the simple class name was displayed.

chore(gui): optimized the text search for classes, methods and fields

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

Implement resources key renaming suggested by @jpstotz in #844

feat(res): rename resources keys if contains unprintable chars or duplicates (#844)

---

build.gradle

Exclude project build directories from code style checking

---

README.md

Fixed a small grammar issue in the readme

Fixed grammar slightly

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

Adds support for renaming classes and fields by right clicking their name in the left panel. 
As requested in my comment https://github.com/skylot/jadx/issues/987#issuecomment-703030051.

Rename classes and fields by right clicking their name in left panel.

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

Fix: use lowercase for resource filename and only use underscore for compatibility with newer android studio (#1043)
```
'R' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```
PS: I don't know whether this commit could cause a problem on older android studio or not tho, since i don't have an old one. 
Anyone willing to test this out?
PPS: Even on newer android studio there will be more resource issues that need to be resolved in order to build the APK, but it seems to be unrelated to resource filename rules (something like: `\src\main\res\values\styles.xml:933:5-946:13: AAPT: error: expected flags but got (raw string) 30.`)

fix: use lowercase for resource filename and only use underscore

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java

Currently, the scroll speed in settings is very slow (At least in Linux, I couldn't test in other platforms). This PR increases its speed.
Before:
https://user-images.githubusercontent.com/29029632/102722836-9a145d00-42e2-11eb-8fb8-53b247c48726.mp4
After:
https://user-images.githubusercontent.com/29029632/102722826-8832ba00-42e2-11eb-8b0e-20024eae1393.mp4

Increase scroll speed in settings

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/core/export/ApplicationParams.java
jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java
jadx-core/src/main/resources/export/app.build.gradle.tmpl
jadx-core/src/main/resources/export/build.gradle.tmpl
jadx-core/src/main/resources/export/settings.gradle.tmpl
jadx-core/src/test/java/jadx/tests/functional/TemplateFileTest.java

This PR updates and improves current export decompiled sources as Gradle project.
- New template variables `versionCode` and `versionName`
- A separate template of `build.gradle` file for the application module
- `settings.gradle` template file to ensure the structure of the project
- The ability to extract `minSdkVersion`, `targetSdkVersion` and application name from `AndroidManifest.xml`
- AGP in root `build.gradle.tmpl` updated from `1.5.0` to `4.0.0`
Related to #1095

New gradle export

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/api/JavaVariable.java
jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/main/java/jadx/core/codegen/MethodGen.java
jadx-core/src/main/java/jadx/core/codegen/RegionGen.java
jadx-core/src/main/java/jadx/core/deobf/DeobfPresets.java
jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-core/src/main/java/jadx/core/dex/info/MethodInfo.java
jadx-core/src/main/java/jadx/core/dex/instructions/args/CodeVar.java
jadx-core/src/main/java/jadx/core/dex/instructions/args/NamedArg.java
jadx-core/src/main/java/jadx/core/dex/instructions/args/VisibleVar.java
jadx-core/src/main/java/jadx/core/dex/nodes/MethodNode.java
jadx-core/src/main/java/jadx/core/dex/nodes/VariableNode.java
jadx-core/src/main/java/jadx/core/utils/CodeGenUtils.java
jadx-gui/src/main/java/jadx/gui/treemodel/JVariable.java
jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/utils/JNodeCache.java
jadx-gui/src/main/java/jadx/gui/utils/JumpPosition.java

#1084 #1023 
enable to rename variables/parameters

enable to rename variable

---

jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties

updated korean

---

jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/ui/ExcludePkgDialog.java
jadx-gui/src/main/java/jadx/gui/ui/JPackagePopupMenu.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

#1151 
Add a tree to select packages for exclude them at the same time, this gives people an opportunity to just analyze the only package they want in an APK, because now we can exclude packages very easily. ✌

Improve exclude package feature

---

jadx-core/src/main/java/jadx/core/xmlgen/ManifestAttributes.java

chore: fix XML attribute decoding

---

jadx-gui/src/main/java/jadx/gui/device/debugger/BreakpointManager.java
jadx-gui/src/main/java/jadx/gui/device/debugger/smali/Smali.java

fix LGTM alerts

---

jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java

fix: fix export to gradle project (#1222)

---

jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

fix a translation error and translate more accurately

update chinese translation

---

jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java

As reported in #1350 and the suggested fix by you (@skylot), I hope it's okay.

Make jobf file hermetic

---

jadx-core/src/main/java/jadx/core/dex/visitors/rename/RenameVisitor.java

A fix for the problem that you mentioned in my other issue #1350

Only mark classes as anonymous if they are a number

---

jadx-core/src/main/java/jadx/core/xmlgen/ManifestAttributes.java

Hopefully this is the final PR to close #1156.
Based on my proposal in https://github.com/skylot/jadx/issues/1156#issuecomment-825660907 I improved decoding of flag attributes.

chore: improved decoding of flag attributes in binary XML files

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java

There were two different actions implemented, one for the context menu and one for the key event. 
Only the latter was copying a snippet to clipboard, the context menu action listener just generated the frida snippet for the garbage collector.

fix: frida context menu entry does nothing

---

jadx-core/src/main/java/jadx/core/dex/trycatch/CatchAttr.java
jadx-core/src/main/java/jadx/core/dex/visitors/AttachTryCatchVisitor.java
jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockExceptionHandler.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TestNestedTryCatch2.java

fix: nested try catch decompilation failed (#1374)

---

jadx-gui/src/main/java/jadx/gui/utils/RelativePathTypeAdapter.java

fix(gui): IllegalArgumentException when saving project to a different directory than the APK file
This PR fixes #1387

fix for #1387 

---

appdata.xml

adds appdata.xml with some metadata about this project, needed for flathub

add appdata.xml

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java

Correction of issue #1434, where it was not possible to set the option `--decompilation-mode`.

fix: bug impossible to set the option "--decompilation-mode"

---

jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java

fix IndexOutOfBoundsException when switching between tabs via mouse wheel
Fix for #1456

fix(gui): fix IndexOutOfBoundsException

---

jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties

I know the guidelines tell you to open an issue first before creating PRs, but I reckoned pointing out all the questionable locations would take longer than simply providing the fix directly

Fix mixed-up quotation marks in lang files

---

jadx-gui/build.gradle

Related issue
#1628 #1606 #1213 #1574 #1552

Fix broken FileDialog

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/LogViewerDialog.java

Improvements as discussed in #1311

[gui]: improve log viewer dialog

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

Fix the abnormal main window initial size in Hi-DPI screen.
Fixes: #1728

fix(gui): hi-dpi main window initial size

---

jadx-core/src/main/java/jadx/core/xmlgen/ProtoXMLParser.java

Special characters in AAB files are not currently encoded. This PR fixes it

Fix encoding special characters in AAB files

---

jadx-gui/src/main/java/jadx/gui/device/debugger/smali/Smali.java

Fix for Issue #1739.  I put a writeup of the bug cause and my fix on the comments of that issue.

Fix for issue #1739

---

jadx-gui/src/main/java/jadx/gui/treemodel/JVariable.java

fix for html rendering problem when renaming varaibles

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/CodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/JsonPrettifyAction.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

Add support to pretiffy json file in resource, it will be more readable.

feat(gui): add an action to prettify json file in resources

---

jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java

Quick & dirty fix for #1891. I know you want to move it to the plugin soon anyway, but at least for now it would be fixed.

Don't override passed mappings path

---

jadx-core/src/main/java/jadx/core/xmlgen/ManifestAttributes.java

My previous commit e1aa9f6 was not complete. I had to use more logic of apktool. My test case was https://apkpure.com/awb-rastatt/de.k4systems.awbrastatt (version 7.2.0). Gradle build now fails with a java issue.

fix(res): resolve all custom attributes

---

jadx-gui/src/main/java/jadx/gui/ui/TabComponent.java
jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

Implements #1939. GUI feature that adds a right-click option on tabs to close all tabs to the right of the selected tab.

feat(gui): close all tabs to the right

---

jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java

I moved `checkForRedirects` implementation into `codeJump`, and generalized it a bit so it would work also for methods and variables.
Now it works for "go to declaration" for inlined nodes.
Fix #1905

Support inline node for jump to code

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/SearchBar.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

Implemented number of search results feature

---

jadx-gui/src/main/java/jadx/gui/device/debugger/ArtAdapter.java
jadx-gui/src/main/java/jadx/gui/device/debugger/DebugController.java
jadx-gui/src/main/java/jadx/gui/device/debugger/DebugSettings.java
jadx-gui/src/main/java/jadx/gui/device/debugger/RegisterObserver.java
jadx-gui/src/main/java/jadx/gui/device/debugger/SmaliDebugger.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/ADBDialog.java

Related issues: #1981 and #1841
This MR contains changes to the debugger to simplify the code to make it easier to understand (it used a lot of generic containers like SimpleEntry).
Also a central method was created to centralize the code that is going wrong in the referenced issues, not yet sure how to finally fix this...

Understanding and may be fixing IndexOutOfBoundsException in the debugger

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

fixed the issue of resourceIds reuse

fix:fixed the issue of resourceIds reuse

---

jadx-core/src/main/java/jadx/core/xmlgen/CommonProtoParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ProtoXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ResProtoParser.java

Sometimes external tools remove all the debug data. In this case, attribute names, namespaces, and values are blank leading to XML parsing errors.

Fixed XML proto parsing for removed debug data

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/ADBDialog.java

To allow the user to select the desired device from the devices listed in the list, I saved the last selected device using the procTree change event

Fixed ADBDialog->launchApp() if multiple devices presented should let user select the one they desire.

---

README.md

I made several improvements to the installation section in the README
* Changed numbering for bullets
* Added shield for jadx-git on the aur
* Made shields consistent style
* Changed shields to redirect to their respective download pages
I am maintaining jadx-git on the aur, so if there's anything that should be changed please let me know

docs: improve installation section

---

jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkManager.java

Fix automated installation and check exit code of executed external commands

Improvements for Quark integration

---

jadx-core/src/main/java/jadx/api/ResourceType.java
jadx-gui/build.gradle.kts
jadx-gui/src/main/java/jadx/gui/ui/panel/ImagePanel.java

This pull request adds feature for preview webp image on gui mode and closing (#2190)

feat(gui): add webp image preview support

---

jadx-core/src/main/java/jadx/core/utils/files/FileUtils.java
jadx-gui/src/main/java/jadx/gui/treemodel/JInputFile.java
jadx-gui/src/main/java/jadx/gui/treemodel/JInputScript.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

This PR adds script rename feature on gui mode. Closes #2354

feat(gui): add script rename feature

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

This PR adds confirm dialog when removing script. Closes https://github.com/skylot/jadx/issues/2353

feat(gui): added confirm dialog when removing script

---

jadx-gui/src/main/java/jadx/gui/utils/pkgs/PackageHelper.java

Non-leaf packages with classes are not visible in the sources tree

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/ui/JadxSettingsWindow.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/AbstractCodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/DynamicCoreAreaTheme.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/SmaliArea.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

This PR add new theme for code editor based on current app theme and dynamic update if theme changed. Maybe fixed  #1763, #1735
Preview: [Googe Drive](https://drive.google.com/file/d/1d0B8ptYq6Rw5URplq7XliomA_SRFKnKi/view?usp=sharing)
https://github.com/user-attachments/assets/4d64b15c-2c90-4825-992c-35f39e55be54

fix(gui): created dynamic theme for code editor

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/tab/TabBlueprint.java
jadx-gui/src/main/java/jadx/gui/ui/tab/TabComponent.java
jadx-gui/src/main/java/jadx/gui/ui/tab/TabsController.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

This PR adds feature named as "Enable Prewiew Tab" taken from Inteliji Idea. Tab is opened with the content of the node, but if we click on another node, the content of these tab is replaced by the new one and if existing opened node , we a jumped to it.
Close #756
https://github.com/user-attachments/assets/ece963c0-1e2e-4c85-8ced-3070c2fcc097

Added Preview Tab Feature

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

A "Copy All" button has been added, allowing users to copy the search results through this button for convenient record-keeping.

Add copy all button in CommonSearchDialog

---

jadx-gui/src/main/java/jadx/gui/ui/tab/TabComponent.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

This PRs added added feature to close all left tabs (fix #1390)

Added feature to close all left tabs (fix #1390)

---

jadx-gui/src/main/java/jadx/gui/treemodel/JClass.java
jadx-gui/src/main/java/jadx/gui/treemodel/JField.java
jadx-gui/src/main/java/jadx/gui/treemodel/JMethod.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

This PRs adds restore tree state after renaming (fix #2485)

Restore tree state after renaming

---

jadx-gui/src/main/java/jadx/gui/treemodel/JResource.java

fix(gui): update resource.arsc nodes after opened tab with resource ids

---

jadx-gui/build.gradle.kts
jadx-gui/src/main/java/jadx/gui/utils/tools/NLSAddNewLines.java
jadx-gui/src/main/java/jadx/gui/utils/tools/SyncNLSLines.java
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties

This PRs adds:
This is a good useful changes and solves when it used to have to be make it manually.

Update NLSAddNewLines tool

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/utils/pkgs/JRenamePackage.java
jadx-gui/src/main/java/jadx/gui/utils/pkgs/PackageHelper.java

Related to https://github.com/skylot/jadx/issues/1590#issuecomment-2895788206

fix(gui): fix rename package behaviors

---

jadx-gui/src/main/java/jadx/gui/settings/ui/JadxSettingsWindow.java
jadx-gui/src/main/java/jadx/gui/ui/cellrenders/PathHighlightTreeCellRenderer.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/ExcludePkgDialog.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/UsageDialogPlus.java
jadx-gui/src/main/java/jadx/gui/ui/panel/SimpleCodePanel.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

1. Added themed color in UsageDialogPlus https://github.com/skylot/jadx/pull/2503#issuecomment-2902561755 and refactored code
2. Added padding between buttons in package exclusion dialog and fixed crash when root package clicked
3. Added padding between buttons in settings dialog
4. Update EN translation added in #2503, #2498

Simple improve ui

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/GotoAddressDialog.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/SearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/hexviewer/HexSearchBar.java
jadx-gui/src/main/java/jadx/gui/utils/HexUtils.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java

1. Use check if entered valid hex address from GotoAddressDialog
2. Make error style search field if hex search value not valid in hex viewer

chore: use check if entered valid hex address from GotoAddressDialog

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/SearchDialog.java

fix(gui): fixed incorrectly handles full window repaint in search dialog

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ParserStream.java

Fixes issue #2535 where plain text XML files are loaded/extracted as empty or truncated files.

fix(core): fix loading plain text XML files

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java

fix NullPointerException in copyAllSearchResults (#2580)

fix(gui): fix NullPointerException in copyAllSearchResults (#2580)

---

README.md
jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/core/dex/visitors/typeinference/TypeUpdate.java
jadx-core/src/main/java/jadx/core/dex/visitors/typeinference/TypeUpdateInfo.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/ui/JadxSettingsWindow.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

* Fix for the "Type inference error: updates count limit reached"
* Users will be able to choose the limit and possibly avoid this error
* Adding options on decompilation settings
This is a fix for the '"Type inference error: updates count limit reached" found on #2585
I did not test with the method passed because only the failed method was provided (not sure how to test in this case).
However, I have tested with the following code https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/content/pm/PackageParser.java#4028 
<details>
<summary> Without modifying type update limit parameter </summary>
```java
/*  JADX ERROR: Type inference failed
jadx.core.utils.exceptions.JadxOverflowException: Type inference error: updates count limit reachedwith updateSeq = …
```

Fix Type inference error: updates count limit reached

---

jadx-cli/build.gradle.kts
jadx-gui/src/main/java/jadx/gui/ui/filedialog/FileDialogWrapper.java
jadx-plugins/jadx-apks-input/build.gradle.kts
jadx-plugins/jadx-apks-input/src/main/java/jadx/plugins/input/apks/ApksCustomCodeInput.kt
jadx-plugins/jadx-apks-input/src/main/java/jadx/plugins/input/apks/ApksCustomResourcesLoader.kt
jadx-plugins/jadx-apks-input/src/main/java/jadx/plugins/input/apks/ApksInputPlugin.kt
jadx-plugins/jadx-apks-input/src/main/resources/META-INF/services/jadx.api.plugins.JadxPlugin
settings.gradle.kts

feat: support .apks file
