jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/build.gradle
jadx-core/src/main/java/jadx/api/DefaultJadxArgs.java
jadx-core/src/main/java/jadx/api/IJadxArgs.java
jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/api/JavaClass.java
jadx-core/src/main/java/jadx/api/JavaPackage.java
jadx-core/src/main/java/jadx/core/codegen/ClassGen.java
jadx-core/src/main/java/jadx/core/codegen/MethodGen.java
jadx-core/src/main/java/jadx/core/deobf/DefaultDeobfuscator.java
jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-core/src/main/java/jadx/core/deobf/IDeobfuscator.java
jadx-core/src/main/java/jadx/core/deobf/PackageNode.java
jadx-core/src/main/java/jadx/core/deobf/StubDeobfuscator.java
jadx-core/src/main/java/jadx/core/dex/visitors/DotGraphVisitor.java
jadx-core/src/main/java/jadx/core/dex/visitors/SaveCode.java

Added deobfuscation feature (basic functionality).
New command line options:
--deobf                Activate deobfuscating
--deobf-min            The minimum length of a name. The name with a length less
than this value will be subjected deobfuscating (default is 2)
--deobf-max            The maximum length of a name. The name with a length great
than this value will be subjected deobfuscating (default is 40)
--deobf-rewrite-cfg    Forced rewrite map of deobfuscation
Now deobfuscation applied to name of classes and name of packages. In the future it will also apply to fields and methods.
If not exists it creates a file with map of deobfuscation (this file located in same directory as the APK file and has the extension **jobf**)
Each line represents an alias in the following format
{type} …

core: added deobfuscation feature (basic functionality)

---

jadx-gui/build.gradle

I dislike that currently you have to start jadx-gui using a very complex startup-script that in the end just sets the classpath and the main class, something Java can just read out from the MANIFEST.MF of the main jar file.
Therefore I extended the build.gradle script of the jadx-gui subproject to add the required entries to the MANIFEST.MF of jadx-gui.jar.
This allows to start jadx-gui simply by executing "`javaw -jar jadx-gui-0.6.1-dev.jar`"
Tested with gradle 2.3

Make jadx-gui.jar runnable

---

jadx-gui/src/main/java/jadx/gui/ui/MainDropTarget.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

This patch enabled Jadx-gui to accept files via drag & drop from external applications (e.g. file explorer). The dropped file will be loaded.

Enable file drop operation for loading it.

---

jadx-core/src/main/java/jadx/core/deobf/PackageNode.java

Deobfuscation terminated when the APK file has classes that is in the root package
```
16:55:52 ERROR - Visitor init failed: RenameVisitor
java.util.EmptyStackException: null
at java.util.Stack.peek(Unknown Source) ~[na:1.7.0_71]
at java.util.Stack.pop(Unknown Source) ~[na:1.7.0_71]
at jadx.core.deobf.PackageNode.getFullAlias(PackageNode.java:64) ~[jadx-core-0.6.1-dev.jar:na]
at jadx.core.deobf.DeobfClsInfo.getFullName(DeobfClsInfo.java:36) ~[jadx-core-0.6.1-dev.jar:na]
at jadx.core.deobf.Deobfuscator.getClassFullName(Deobfuscator.java:526) ~[jadx-core-0.6.1-dev.jar:na]
at jadx.core.deobf.Deobfuscator.processClass(Deobfuscator.java:237) ~[jadx-core-0.6.1-dev.jar:na]
at jadx.core.deobf.Deobfuscator.process(Deobfuscator.java:105) ~[jadx-core-0.6.1-dev.jar:na]
at …
```

fix deobfuscation

---

jadx-cli/build.gradle
jadx-gui/build.gradle

Hi I tune the heap limit for jadx-cli and jadx-gui to get rid of most OOMs encountered when dealing with real-world apks.
Both would have Xms=2G and Xmx=4G, reasonable for dev PCs nowadays.

Increase heap limit to avoid most OOMs in Gradle

---

jadx-core/src/main/java/jadx/core/utils/files/InputFile.java

we should consider the input file could contain only one single dex, multi-dex, or instantRun support dex for Android .apk files

support for Android InstantRun Apk

---

jadx-core/src/main/java/jadx/core/codegen/ClassGen.java
jadx-core/src/main/java/jadx/core/codegen/MethodGen.java
jadx-core/src/main/java/jadx/core/codegen/NameGen.java
jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-core/src/main/java/jadx/core/dex/info/ClassInfo.java
jadx-core/src/main/java/jadx/core/dex/info/FieldInfo.java
jadx-core/src/main/java/jadx/core/dex/info/InfoStorage.java
jadx-core/src/main/java/jadx/core/dex/info/MethodInfo.java
jadx-core/src/main/java/jadx/core/dex/nodes/DexNode.java
jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java

Fixes the following issues with deobfuscation:
- Name generation on variables of deobfuscated objects were sometimes based off of the original class name, and not the alias.
- Renamed classes/methods referenced in a different dex file would not be renamed properly.
- Deobfuscator.postProcess may overwrite Deobfuscated method names for overriden methods.
Also fixes one issue not related to the  deobfuscation:
- Inner classes residing in an empty package name were not being linked to their parent class due to an issue with ClassInfo.splitNames
Thanks for this project!

Deobfuscation fixes

---

jadx-core/src/main/java/jadx/core/codegen/CodeWriter.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

Because of forgotten replacements invalid XML code was generated like
```xml
<?xml version="1.0" encoding="utf-8"?>
<defpackage.x xmlns:android="http://schemas.android.com/apk/res/android" xmlns:twitter="http://schemas.android.com/apk/res-auto"
</x>
```

Fixes errors

---

jadx-core/src/main/java/jadx/core/utils/files/FileUtils.java

The correct pattern to make a directory is: `if (!dir.mkdirs() && !dir.isDirectory()) { error }` mkdirs checks for exists so the exists check is redundant.

Directory Bug

---

jadx-gui/src/main/java/jadx/gui/utils/CertificateManager.java

Improve performance by using StringBuilder instead of StringBuffer.

Performance issue when building strings

---

jadx-core/src/main/java/jadx/core/codegen/ClassGen.java

Originally I wanted to make the complete class name including package name clickable. But I did not manage to do so as it seems like I can not specify the clickable text section manually. Now at least the class name is clickable

make the import class name clickable

---

jadx-gui/src/main/java/jadx/gui/jobs/BackgroundJob.java

Currently the DecompileJob generates the background jobs for decompiling the classes and then returns. 
Then the ShutdownTask is triggered which waits up to 5 minutes and then continues even if decompile jobs are still running.
If the decompilation of the remaining jobs requires more than 5 minutes Jadx is running into troubles:
This means that it starts indexing when decompilation is still running and therefore all data structures by Jadx don't cover the whole app. 
Alls this is visible to the user as the progress bar disappears way too early. Even is the CPU utilization shows that decompilation is still running.
For large APKs 5 minutes is way too less. I used the Facebook app linked in #354 and was still busy processing decompile job 5077 of 104946 when the ShutdownTask finally …

Decompilation and indexing are messed-up for large apps

---

jadx-gui/src/main/java/jadx/gui/ui/SearchDialog.java
jadx-gui/src/main/java/jadx/gui/utils/search/CodeIndex.java

fix: unsynchronized search index creation results in NullPointerException upon performing search:
```
java.lang.NullPointerException: null
at jadx.gui.utils.search.CodeIndex.isMatched(CodeIndex.java:40)
at jadx.gui.utils.search.CodeIndex.lambda$search$0(CodeIndex.java:49)
at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.subscribe(Flowable.java:14752)
at io.reactivex.internal.operators.flowable.FlowableConcatArray$ConcatArraySubscriber.onComplete(FlowableConcatArray.java:140)
at io.reactivex.internal.operators.flowable.FlowableConcatArray.subscribeActual(FlowableConcatArray.java:40)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at …
```

Search causes NullPointerException

---

jadx-gui/src/main/java/jadx/gui/ui/HeapUsageBar.java
jadx-gui/src/main/java/jadx/gui/utils/CodeUsageInfo.java

Unsynchronized search index creation (code usage) results in ArrayIndexOutOfBoundsException makes the index creation stuck at 99%
This also fixes #354 (Facebook messenger using -Xmx12g using Java 11) in my tests.
Additionally I included a small fix for the heap usage bar which turned "red" too early.

fix: unsynchronized search index creation 

---

jadx-gui/src/main/java/jadx/gui/ui/HeapUsageBar.java
jadx-gui/src/main/java/jadx/gui/utils/Utils.java

During some real-work tests with jadx using a heap size of 10-12 GiB the spare memory calculated by `isFreeMemoryAvailable()` was way larger that actually necessary. Jadx never requires 2-2.5 GiB just to run.

fix: limit the spare memory to max. 512MiB

---

jadx-gui/build.gradle

The G1GC is way faster and therefore often helps to reduce the memory usage when running Jadx wit Java 8. On Java9+ G1GC is already the default GC, therefore the G1GC flags don't change anything for that runtime platforms. 
I had problems when compiling with OpenJDK 11. The created jadx-gui-dev.exe file said it requires Java 11 (and links to the Oracle Java 8 page) but it wasn't able to find the installed OpenJDK 11 version. With compilation target Java 8 it is at least able to find an installed Java 8 JRE.

build: compile for Java 8; enable G1GC on Java 8

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/core/Jadx.java
jadx-core/src/main/java/jadx/core/dex/info/AccessInfo.java
jadx-core/src/main/java/jadx/core/dex/nodes/MethodNode.java
jadx-core/src/main/java/jadx/core/dex/visitors/FixAccessModifiers.java
jadx-core/src/test/java/jadx/core/dex/info/AccessInfoTest.java
jadx-core/src/test/java/jadx/tests/api/SmaliTest.java
jadx-core/src/test/java/jadx/tests/integration/debuginfo/TestLineNumbers2.java
jadx-core/src/test/java/jadx/tests/integration/enums/TestEnums2.java
jadx-core/src/test/java/jadx/tests/integration/inner/TestInnerClassSyntheticRename.java
jadx-core/src/test/java/jadx/tests/integration/others/TestBadMethodAccessModifiers.java
jadx-core/src/test/smali/others/TestBadMethodAccessModifiers/TestCls$A.smali
jadx-core/src/test/smali/others/TestBadMethodAccessModifiers/TestCls$B.smali
jadx-core/src/test/smali/others/TestBadMethodAccessModifiers/TestCls.smali
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties

This PR fix visibility access modifies for methods (see discussions in #370 and #387):
Short description:
* all virtual methods become public
* direct methods become private (instead constructors and static methods for now)
* such modifications perform by default and can be disabled by the option in preferences (`--respect-bytecode-access-modifiers` in jadx-cli)
* if changed to method added comment (`Access modifiers changed, original: private`)
If anyone has any suggestions, please leave a comment.

Fix not allowed access modifiers for methods

---

jadx-core/src/main/java/jadx/core/utils/android/AndroidResourcesUtils.java
jadx-core/src/main/java/jadx/core/utils/files/InputFile.java

APKs without code are getting more and more common.
Originally this was only possible for apps that were implemented purely in native code (never encountered such an app) but nowadays because of the [App Bundle technology](https://developer.android.com/platform/technology/app-bundle/) a lot of apps are constructed out of multiple APK files (e.g. base bundle with the code, the images, the language strings and finally the native libraries).
This PR makes it possible to open such "resource APKs" in Jadx.

fix(gui): Allow APK files without code (no contained dex files)

---

jadx-core/src/main/java/jadx/core/utils/android/AndroidResourcesUtils.java

Hello, current generated field name for style resources in R class
```
/* added by JADX */
/* renamed from: Base.Widget.AppCompat.ImageButton */
public static final int f3775BaseWidgetAppCompatImageButton = 2131624131;
```
Should be:
```
public static final int Base_Widget_AppCompat_ImageButton = 2131624131;
```

fix: replace dot character with underscore in style resource name

---

jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java
jadx-gui/src/main/java/jadx/gui/treemodel/JPackage.java
jadx-gui/src/main/java/jadx/gui/treemodel/JSources.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

This is related to #423.
The changes does the following:
- On right-click of a package, it opens a menu to exclude/unexclude.
- Propagates this change to the settings.
- Refresh the tree.
- Excluded packages don't show children.

GUI: disable package if "excluded"

---

jadx-gui/src/main/java/jadx/gui/treemodel/JResource.java

The Resources section should be sorted, for better experience.
They are made sorted according to their type (ROOT, then DIR, then FILE), then sorted by name (case-insensitive).

GUI: Sort resources according to their type, then name

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/core/codegen/AnnotationGen.java
jadx-core/src/main/java/jadx/core/codegen/ClassGen.java
jadx-core/src/main/java/jadx/core/codegen/MethodGen.java
jadx-core/src/test/java/jadx/tests/integration/generics/TestImportGenericMap.java

This happens when the generics type is an inner class.

Fix missing import for class Generics map.

---

jadx-core/src/main/java/jadx/core/xmlgen/entry/ValuesParser.java
jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-samples/src/main/java/jadx/samples/TestCF4.java

As detected by Eclipse, and the test case doesn't depend on the explicit
casting.

Remove unneeded cast.

---

jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java

Currently Jadx does not generate quantity attribute for plurals.

fix: quantity attribute for plurals

---

jadx-core/src/main/java/jadx/core/xmlgen/ParserStream.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java
jadx-core/src/main/java/jadx/core/xmlgen/entry/EntryConfig.java

Currently Jadx does not properly generates configuration qualifiers. [Example apk](https://drive.google.com/file/d/1CwUTCvJZv4iWqVuKQ4aRNfZ94qAO-yLz/view?usp=sharing). In values-h1dp-land-v13 You can see duplicate resource values (there not only duplicates, but also resources from other configurations) like
```
<dimen name="PopupLayoutList_height">270dp</dimen>
<dimen name="PopupLayoutList_height">300dp</dimen>
```
I fixed it. Almost all the code for fix was copied from apktool

fix: resource configuration qualifiers

---

jadx-gui/src/main/java/jadx/gui/ui/AboutDialog.java

In the GUI "About" dialog: so the users sees something like `1.8.0_202` instead of `25.202-b08`

gui: better to show java version, instead of VM version

---

jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-core/src/main/java/jadx/core/dex/attributes/AFlag.java
jadx-core/src/main/java/jadx/core/utils/android/AndroidResourcesUtils.java

Hello, when deobfuscation processes fields, it does not check whether alias is already set in `FieldInfo`. As a result, you can see that the class R fields are renamed twice.
Without deobfuscation (alias set by `AndroidResourcesUtils`):
```
public static final class array {
/* renamed from: enum */
public static final int pref_widget_font_sizes = 2131689474;
/* renamed from: ll1l */
public static final int widget_theme_entries = 2131689473;
/* renamed from: null */
public static final int pref_widget_font_families = 2131689475;
}
```
With deobfuscation (alias set by `AndroidResourcesUtils` and then replaced by `Deobfuscator`):
```
public static final class array {
/* renamed from: enum */
public static final int f2654enum = 2131689474;
/* renamed from: ll1l */
public static final int …
```

fix: R class fields alias

---

jadx-core/src/test/java/jadx/tests/api/IntegrationTest.java
jadx-core/src/test/java/jadx/tests/api/utils/TestUtils.java
jadx-core/src/test/java/jadx/tests/integration/TestStaticFieldsInit.java
jadx-core/src/test/java/jadx/tests/integration/arith/TestFieldIncrement2.java
jadx-core/src/test/java/jadx/tests/integration/arrays/TestArrayFill2.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions3.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestNestedIf2.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestTernary2.java
jadx-core/src/test/java/jadx/tests/integration/debuginfo/TestReturnSourceLine.java
jadx-core/src/test/java/jadx/tests/integration/inner/TestAnonymousClass5.java
jadx-core/src/test/java/jadx/tests/integration/invoke/TestCastInOverloadedInvoke.java
jadx-core/src/test/java/jadx/tests/integration/loops/TestLoopDetection3.java
jadx-core/src/test/java/jadx/tests/integration/loops/TestSynchronizedInEndlessLoop.java
jadx-core/src/test/java/jadx/tests/integration/others/TestIssue13a.java
jadx-core/src/test/java/jadx/tests/integration/synchronize/TestSynchronized2.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TestFinally2.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TestTryCatch5.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TestTryCatchFinally2.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TestTryCatchFinally5.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TryAfterDeclaration.java
jadx-core/src/test/java/jadx/tests/integration/types/TestTypeResolver3.java

This change does two things:
1. Replaces commented `TODO` to a `@NotYetImplemented` tests
2. Add the `@ExtendWith(NotYetImplementedExtension.class)` to TestUtils, so we we don't need to add it to every sub-class.

test: use @NYI instead of commented TODO

---

jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/treemodel/JPackage.java

1. In a previous commit, `JadxWrapper.getExcludedPackages()` would return a list of empty string"" when we have no exclusion, which causes `getIncludedClasses()` to always return empty list. This PR fixes it.
2. Currently, if we exclude `android`, then both `android` and `androidx` packages are disabled, which shouldn't be the case.
The implementation checks if they both are exact match, or the full package name starts by the "exclusion" + '.'

fix(gui): exclusion disablement should be exact package match

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java

This change accepts the stored windows positions only if they are completely inside one of the visible screens, otherwise show it by the default location in the default screen.
The reason of this, if a user changes from two screens to one screen, then he won't be able to see the windows at all.
Ideally, we should check if a part of the window is inside the screen, or if the window is split between two screens, but I don't think this is necessary at this time.

fix(gui): detect if a window is opened inside a visible screen

---

jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions13.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions14.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions15.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions2.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestNestedIf.java

`private` was made `public` to fix Eclipse warning. It doesn't affect the test behavior.

test: make test @NYI instead of commenting assertions

---

jadx-core/src/main/java/jadx/core/deobf/DeobfPresets.java
jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java

Java NIO Path is the new way to handle files.
This is a first step to move forward, more steps could be to change InputFile to have internal Path, but I am not sure about backward compatibility constraints for the API.
BTW, would it be helpful if Java 11 is used?

chore: use Path instead of File

---

jadx-core/src/main/java/jadx/core/utils/StringUtils.java

The reason is, if `.toString()` is called with string concatenation, then a `StringBuilder` is used. In the changed code, we already have a `StringBuilder`.
To verify this: the java bytecode of:
```
public String test() {
StringBuilder b = new StringBuilder();
return '"' + b.toString() + '"';
}
```
is:
```
public java.lang.String test();
Code:
0: new           #2                  // class java/lang/StringBuilder
3: dup
4: invokespecial #3                  // Method java/lang/StringBuilder."<init>":()V
7: astore_1
8: new           #2                  // class java/lang/StringBuilder
11: dup
12: invokespecial #3                  // Method java/lang/StringBuilder."<init>":()V
15: bipush        34
17: invokevirtual #4                  // Method …
```

chore: don't create unneeded StringBuilder

---

jadx-core/src/main/java/jadx/core/dex/info/MethodInfo.java
jadx-core/src/main/java/jadx/core/dex/instructions/InvokeNode.java
jadx-core/src/main/java/jadx/core/dex/visitors/SimplifyVisitor.java
jadx-core/src/test/java/jadx/tests/integration/others/TestStringConstructor.java

Fixes #530
`test4()` fails, because I don't know how to get the actual value of the array.
In other words: the code generated is:
```
public static class TestCls4 {
public String tag = new String(new byte[] {0, 1, 2, 'a', 'b', 'c'});
}
public TestStringConstructor$TestCls4() {
byte[] bArr = new byte[6];
bArr[1] = (byte) 1;
bArr[2] = (byte) 2;
bArr[3] = (byte) 97;
bArr[4] = (byte) 98;
bArr[5] = (byte) 99;
this.tag = new String(bArr);
}
```
And in `SimplifyVisitor`, I don't know how to the the actual values of `bArr`, not its definition.

fix: better String constructor from byte and char arrays (#530)

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-gui/src/main/java/jadx/gui/JadxGUI.java
jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/jobs/BackgroundWorker.java
jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsAdapter.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java
jadx-gui/src/main/java/jadx/gui/treemodel/ApkSignature.java
jadx-gui/src/main/java/jadx/gui/ui/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/HeapUsageBar.java
jadx-gui/src/main/java/jadx/gui/ui/MainDropTarget.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/utils/NLS.java
jadx-gui/src/main/java/jadx/gui/utils/PathTypeAdapter.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/test/java/jadx/gui/TestI18n.java

Fix #526 
This is initial change to have basic project, other properties would be separately added.
Changes are:
- Open file can open either file or project
- A project contains currently `projectVersion`, and `filesPath` as a list to support future files without changing format.
- A setting option to `Auto save` projects or not.
- On window close, user is asked to save unsaved project, before proceeding
- `NLS.str` has now `varargs`
- Test was added to check if an i18n property is not used.

gui: support project (#526)

---

jadx-gui/src/main/java/jadx/gui/settings/ISettingsUpdater.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java

And make `JadxSettings.partialSync` private, as I guess it is meant to be internally used.

chore: use functional interface instead of ISettingsUpdater

---

jadx-core/src/test/java/jadx/tests/integration/arith/TestArith.java
jadx-core/src/test/java/jadx/tests/integration/arith/TestArith2.java
jadx-core/src/test/java/jadx/tests/integration/arith/TestFieldIncrement3.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions16.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions8.java

Changes in `TestFieldIncrement3` was done by Eclipse, since they are unneeded casts.

test: use NYI instead of comment

---

jadx-core/src/test/java/jadx/tests/integration/trycatch/TestTryAfterDeclaration.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties

test: fix after the new re-compiling.
Also, rename message in GUI (since it can be used while exiting the application).

fix test and rename GUI message

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

Fix #556 
I am not sure about the format of the resource table format, but key can be -1.

fix: resource entry with -1 key (#556)

---

jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java

When autosave option is enabled, and project is initial, any `changed()` activity will result in `NPE`.

fix(gui): NPE if the autosave is enabled, and project is initial

---

jadx-core/src/main/java/jadx/core/utils/files/InputFile.java
jadx-core/src/main/java/jadx/core/utils/files/JavaToDex.java

fix: handle big .jar files (using multi-dex option) (#390)

---

jadx-core/src/main/java/jadx/core/dex/visitors/ExtractFieldInit.java
jadx-core/src/test/java/jadx/tests/integration/arrays/TestArrayInitField.java
jadx-core/src/test/java/jadx/tests/integration/others/TestFieldInitInTryCatch.java

Similar to #567, but for `static` fields.

fix: remove static field redundant array type when initialized

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java

When opening big file, and changing settings, the window takes long time to reload the file, and user doesn't know if he clicked or not.
This change disables all subcomponents, before opening the file and ultimately close the settings window.

gui: disable all components on saving the settings

---

jadx-core/src/main/java/jadx/core/dex/instructions/InsnDecoder.java
jadx-core/src/main/java/jadx/core/dex/visitors/ExtractFieldInit.java
jadx-core/src/main/java/jadx/core/dex/visitors/ReSugarCode.java

Fix #342 
If an opcode is incorrect, then we shouldn't throw Exception, because this will make the method has no blocks.
Instead, print warning, and replace it with `NOP`, this is also what apktool does.

fix: handle unknown opcodes (#342)

---

jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/main/java/jadx/core/dex/instructions/InsnDecoder.java
jadx-core/src/main/java/jadx/core/dex/instructions/args/ArgType.java
jadx-core/src/main/java/jadx/core/dex/visitors/regions/LoopRegionVisitor.java
jadx-core/src/test/java/jadx/core/dex/visitors/typeinference/TypeCompareTest.java
jadx-core/src/test/java/jadx/tests/functional/SignatureParserTest.java
jadx-core/src/test/java/jadx/tests/integration/generics/TestGenerics7.java
jadx-core/src/test/java/jadx/tests/integration/invoke/TestCastInOverloadedInvoke.java

fix: remove generics cast when object types match (#591)

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java

GUI-related: when there is long class names, upper cases are shown first, then followed by lower case.
I guess it is better to have them all sorted case insensitive, so the needed class can be easily found.

fix(gui): sort classes by case insensitivity

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

Issue https://github.com/skylot/jadx/issues/394
Before
```xml
<string name="">Navigate home</string>
<string name="">Navigate up</string>
```
Now
```xml
<string name="RES_2131755008">Navigate home</string>
<string name="RES_2131755009">Navigate up</string>
```

Generates XML key names if empty

---

jadx-core/src/main/java/jadx/core/dex/instructions/ArithOp.java
jadx-core/src/main/java/jadx/core/dex/instructions/args/InsnArg.java
jadx-core/src/main/java/jadx/core/dex/visitors/PrepareForCodeGen.java

This PR moves changes from #559 from `InsnArg` and `ArithOp` to `PrepareForCodeGen`, which seems to be there before, but was incomplete.

chore: move arithmetic parenthesis logic from InsnArg to PrepareForCodeGen

---

jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java

When a tree node is collapsed, we remove it from the "tree expansions", however opened children still remain in the saved values.
This change recursively removes all sub-children from being saved when a node is collapses.

fix(gui): remove tree children expansions as well

---

jadx-core/src/main/java/jadx/core/utils/files/InputFile.java

By overwriting the created temp file
Fix #631

fix: loading aar/jar files (#631)

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

fix(gui): closing jadx main should terminate the JVM (#639)

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/CodePanel.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/SearchBar.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/SmaliArea.java

Additionally this PR includes a small fixe (start with line 0) for the smali tab and some unnecessary code in JadxDecompiler.java is removed.

feat(gui): make search bar usable for smali code

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/api/JadxDecompiler.java

Decompilation a single single class only was not yet possible. In the backend a flexible Predicate<String> (String=full class name) is used. Therefore implementing different filters would be possible.

feat(cli): decompile only a single class

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsAdapter.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

Works only for non-inner classes

feat(gui): select a class via command-line to open in Jadx

---

jadx-cli/build.gradle
jadx-gui/build.gradle

In `jadx-gui.bat` the command for starting `javaw.exe` contains in the end double double quotes which prevents starting jadx-gui.
This is the fix for issue #692

fix(gui): jadx-gui.bat does not work (#692)

---

jadx-core/src/main/java/jadx/core/dex/nodes/DexNode.java

As described in #763 Jadx silently stops loading classes form an APK like com.whatsapp 2.19.274 (452992) which causes one class loading to fail.
This PR changes the class loading behavior in a way that only the affected class is not loaded. In case of an error the error is logged and class loading continues.

fix: don't stop loading classes in case of an error

---

jadx-gui/build.gradle
jadx-gui/src/main/java/jadx/gui/treemodel/ApkSignature.java

The old apk signature test had problems if the APK contained a v3 signature. 
The updated apksig library can handle v1-v3 signatures correctly. 
Furthermore I moved the verification warnings below the signature block as there are usually a lot of them, but they are not more important that the signature verification result.

feat(gui): Support for APK signature v3 added

---

jadx-core/src/main/java/jadx/api/JavaClass.java
jadx-core/src/main/java/jadx/core/dex/nodes/ClassNode.java
jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java

Try to reload opened tabs on file reload caused by toggling the Deobfuscation option.
Closes #792 issue.
Save a list of opened tabs and scroll positions for each tab, and try to restore opened tabs after reopening file.
Scroll position may be restored not exactly due to comments in the code (like "Renamed from:"), but usually it will be restored closely to original position.

Try to restore opened tabs on file reload

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/api/JavaClass.java
jadx-core/src/main/java/jadx/api/JavaField.java
jadx-core/src/main/java/jadx/api/JavaMethod.java
jadx-core/src/main/java/jadx/core/dex/nodes/ClassNode.java
jadx-gui/src/main/java/jadx/gui/JadxWrapper.java
jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/CodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/RenameAction.java
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

This request adds a Rename popup menu item that allows the user to rename classes, methods and fields.
It is useful for obfuscated code, it makes it much easier to read.
The implementation is very basic and perhaps not optimal, but it works.
I'm working for a better implementation which will not reload whole file at every rename, but it's still in progress.
This request is related to issue #791 but does not completely closes it - there is a place for improving this implementation,
However, no feature is worse than slow, but working feature - so, it's will be good to merge current implementation and then improve it.

Add support for renaming methods, classes and fields

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

Fixes injection of xmlns: attributes from other files (#796)

core: BinaryXMLParser: Reset nsMap in parse()

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

:exclamation: Please review the [guidelines for contributing](../CONTRIBUTING.md#Pull-Request-Process)
Ok.
"./gradlew clean build dist" check passed.
Commit 9c88f70 broked "--select-class" command-line option for jadx-gui.
jadx-gui fails to open specified class, because file is not loaded yet and decompiler.getClasses() returns null, which causes NPE:
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
at jadx.gui.JadxWrapper.searchJavaClassByClassName(JadxWrapper.java:146)
at jadx.gui.ui.MainWindow.processCommandLineArgs(MainWindow.java:204)
at jadx.gui.ui.MainWindow.init(MainWindow.java:195)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at …

gui: Fix --select-class option (regression)

---

jadx-core/src/main/java/jadx/core/dex/nodes/ClassNode.java
jadx-core/src/main/java/jadx/core/utils/SmaliUtils.java

This pull request solves bug #802
The smali code of inner classes is now appended to the shown smali code of non-inner class.

fix: additionally show smali code of inner classes

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

Add Kotin metadata parsing functionality for class and package names. Resolve #758

Add classname parsing for Kotlin metadata

---

jadx-core/src/main/java/jadx/core/dex/nodes/ClassNode.java

With this PR request the smali code generation is changed to consider no only inner classes but also all inner classes of inner classes down to an unlimited recursion level. 
Therefore applying this PR fixes #848.

fix for issue #848 - additionally show smali code of all inner classes (recursively)

---

jadx-gui/src/main/java/jadx/gui/utils/JNodeCache.java

By chance I encountered in the Jadx log several java.lang.ClassCastException java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode in `JNodeCache.makeFrom()`.
Based on some research this can happen in case the HashMap is accesses concurrently. 
This seem to happen very very rarely as I wasn't able to reproduce this Exception in my further tests.
Nevertheless one time if failed and therefore I would suggest to better to use a ConcurrentHashMap for the JNodeCache.

fix: concurrent access may cause an java.lang.ClassCastException

---

jadx-core/src/main/java/jadx/core/codegen/ClassGen.java
jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/test/java/jadx/tests/integration/inner/TestAnonymousClass14.java

When classes are inlined it is not that easy to get the original class name, e.g. if you want to compare it in a different decompiler or if you need the class name for a different purpose like an Xposed module or a Frida script.
Therefore I changed the code generator to add a comment line containing the full class name of the inlined class.

chore: add inlined class name as comment

---

jadx-core/src/main/java/jadx/core/Jadx.java
jadx-core/src/main/java/jadx/core/dex/attributes/AFlag.java
jadx-core/src/main/java/jadx/core/dex/instructions/args/RegisterArg.java
jadx-core/src/main/java/jadx/core/dex/visitors/FindSuperUsageVisitor.java
jadx-core/src/test/java/jadx/tests/integration/others/TestShadowingSuperMember.java
jadx-core/src/test/smali/others/TestShadowingSuperMember/A.smali
jadx-core/src/test/smali/others/TestShadowingSuperMember/B.smali
jadx-core/src/test/smali/others/TestShadowingSuperMember/C.smali

The library erroneously used `this.` modifier before a member variable even if the member variable was declared in the super class (for an example, see the [comment](https://github.com/acsbendi/jadx/blob/88e1e7277b9ec7d53749011761b7c89c1795f6d6/jadx-core/src/test/java/jadx/tests/integration/others/TestShadowingSuperMember.java#L14) in the test I added). The modifications I made will put replace `this.` with the correct `super.` keyword in these cases. I found this issue in a real, obfuscated Android APK where the member variable of the super class was shadowed by that of the subclass.
I added a test including smali files. These present the issue quite well, since without the changes I made, the library fails to even create code that compiles.

Fixed adding this. instead of super. when super member is shadowed

---

jadx-gui/src/main/java/jadx/gui/treemodel/JField.java
jadx-gui/src/main/java/jadx/gui/treemodel/JMethod.java
jadx-gui/src/main/java/jadx/gui/treemodel/JNode.java
jadx-gui/src/main/java/jadx/gui/ui/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/ui/TabComponent.java
jadx-gui/src/main/java/jadx/gui/ui/UsageDialog.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java
jadx-gui/src/main/java/jadx/gui/utils/search/TextSearchIndex.java

The search for methods/fields currently only allows to search for the method/field name, but not for the type or the method arguments.
I extended the text index so that the search text is identical to the displayed text (just without the HTML formatting). This allows to search for methods with a specific method signature.
Because the `JMethod` and `JField` `makeLongString()` implementations were returning HTML formatted text I has to introduce the new methods, `makeStringHtml()` and `makeLongStringHtml()` can be used to return a html formatted representation. Therefore the default implementations now only return plain text data. I only needed `makeLongString()` / `makeLongStringHtml()` but for consistency I also applied this scheme to `makeString()` / `makeStringHtml()`.

Allow to search for full method/field signature

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java

During the last months I had problems with the preferences dialog on my Full-HD monitor on Windows because of it's height:
The button bar at the bottom of the preferences dialog was always shown behind the Windows task bar and therefore inaccessible. I changed the layout to a two-column layout that IMHO fits better to the most monitors.
Additionally the ESC key allows to abort and close the preferences dialog.

chore(gui): preferences dialog changed to two-column mode

---

jadx-gui/build.gradle

In this way, people can execute jadx-gui-1.1.0-no-jre.exe easily.  
@see Respect JAVA_HOME environment variable in Windows intead of Windows Registry #890

Use env %JAVA_HOME% as the JrePath

---

jadx-core/src/main/java/jadx/core/xmlgen/ParserConstants.java
jadx-core/src/main/java/jadx/core/xmlgen/entry/ValuesParser.java

A first attempt to fix #919
In the end `TYPE_DYNAMIC_REFERENCE` seem to work identical to `TYPE_REFERENCE`. Not sure if Jadx already resolves those resources and therefore we don't have to make a difference...
The type `TYPE_DYNAMIC_ATTRIBUTE` has been added, but resources of that type can't be processed yet. An example APK would be helpful for this type.

XML parsing: handling of TYPE_DYNAMIC_REFERENCE entries

---

jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java

This PR added the missing functionality identified in #931 
@skylot I am not sure why but I had some serious problems with the `gradlew check -x test` test. Unless I make a clean before executing this the test very often fails because of format violations in the `:spotlessMisc` test for the files `jadx-cli\build\reports\checkstyle\*.xml` (e.g. main.xml). 
I am not sure if the test is designed to also include the build directory (hence generated files), I would have assumed it is only for checking src files. Is it possible to exclude the build directories from code style tests?

chore(core): resource XML generation for parent attribute added

---

jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

Done.
The rename functionality relies on deobfuscation for now - so let the user know
this and ask the user to enable deobfuscation to get rename working.
The "Force rewrite deobfuscation map file" option effectively disables
renaming, because renaming relies on deobfuscation map modification for now,
but Force rewrite rewrites the map on each file reload, destroying changes.
So. let the user know this issue instead of silent failure.
TODO: Split rename map and deobfuscation map (for example, load the rename map
file after deobfuscation map file to override auto-generated aliases).

gui: RenameDialog: Warn user if deobfuscation settings are invalid.

---

jadx-gui/build.gradle

As described at the end of #949 launch4j exe startup wrapper does not apply maximum heap configuration correctly. This PR fixes the problem.

fix (gui): launch4j maximum heap

---

jadx-gui/src/main/java/jadx/gui/ui/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/ui/SearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/UsageDialog.java

The `Rename` function needs `usageInfo` to change all the references of the name changed. We need to make sure `indexJob` has completed before `Rename`.
Fix #907.

Run indexJob before rename

---

jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/core/clsp/ClsSet.java
jadx-core/src/main/java/jadx/core/xmlgen/ResourcesSaver.java
jadx-plugins/jadx-dex-input/src/main/java/jadx/plugins/input/dex/DexFileLoader.java
jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/utils/LimitedInputStream.java
jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/utils/ZipSecurity.java

Fix to prevent zipbomb forged headers attacks. See issue #980.
Input stream for zip entry wrapped by new LimitedInputStream which don't allow to read more than the expected size of entry.
Also, zip entries count is limited to prevent file creation spam.

fix: prevent zipbomb forged headers attacks

---

jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java

On Windows, the default charset depends on system settings 🤕

fix(gui): use correct charset when writing mapping file

---

jadx-core/src/main/java/jadx/api/ResourceFile.java
jadx-core/src/main/java/jadx/api/ResourceFileContent.java
jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java
jadx-core/src/main/java/jadx/core/xmlgen/ResContainer.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java
jadx-core/src/main/java/jadx/core/xmlgen/ResourceStorage.java
jadx-core/src/main/java/jadx/core/xmlgen/entry/ResourceEntry.java
jadx-core/src/test/java/jadx/tests/api/IntegrationTest.java
jadx-gui/src/main/java/jadx/gui/treemodel/ApkSignature.java
jadx-gui/src/main/java/jadx/gui/treemodel/JResource.java
jadx-gui/src/main/java/jadx/gui/treemodel/JRoot.java

Fixes duplicates entries in XML resources

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

My previous PR (#993) erroneously used a null-check for determining if the Rename option should be shown. As result, all nodes had the Rename option shown (but of course it does not work for nodes which are not class/method/field instances).
As this is just a quick fix for an issue in my last PR, I don't think it needs an issue attached (If it does, please tell me).
I'm sorry for pushing broken code to the project. In my future contributions I will try to pay more attention to possible regressions, lol.

Only show renaming option for JClass, JField and JMethod

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

I've noticed an apk with invalid resource keys. E.g.:
```xml
<application android:theme="@style/%!" android:label="@string/~{" android:icon="@mipmap/~" android:allowBackup="true" android:supportsRtl="true">
```
```xml
<PreferenceScreen android:title="@string/!&" android:key="expset" android:summary="@string/~;"/>
```
the last example prevents the XML file from being parsed.

Renames invalid res keys

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ParserConstants.java

Hey, I've noticed the following thing in Google Chrome app
```xml
<uses-permission xmlns:ns17="http://schemas.android.com/apk/res/android" ns17:name="android.permission.CAMERA"/>
<uses-permission xmlns:ns18="http://schemas.android.com/apk/res/android" ns18:name="android.permission.CHANGE_NETWORK_STATE"/>
<uses-permission xmlns:ns19="http://schemas.android.com/apk/res/android" ns19:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION"/>
<uses-permission xmlns:ns20="http://schemas.android.com/apk/res/android" ns20:name="android.permission.FOREGROUND_SERVICE"/>
<uses-permission xmlns:ns21="http://schemas.android.com/apk/res/android" ns21:name="android.permission.GET_ACCOUNTS"/>
<uses-permission xmlns:ns22="http://schemas.android.com/apk/res/android" …
```

Fixes ns value

---

jadx-core/src/main/java/jadx/core/dex/visitors/blocksmaker/BlockSplitter.java
jadx-core/src/test/java/jadx/tests/integration/trycatch/TestTryWithEmptyCatchTriple.java
jadx-core/src/test/smali/trycatch/TestTryWithEmptyCatchTriple.smali

Note: I have *not* created an issue for this even though you require this in your contribution guidelines, because I already developed a patch for my own use and did not want to duplicate any discussion across the issue and the PR. If necessary I can open a separate issue for this bug.
I found this bug when reverse engineering an app. The test case is obviously modified from the original source, but is still representative of the bug.
While the change makes sense to me – adding the synthetic exception handler block should still be done even when the handler instruction is also a TRY_ENTER, and looking at the graph the handler block is inserted at the correct position – I'd still like someone more familiar with the decompiler to look at the change :) All test cases run fine, but you never …

Process exception handler when handler block is start of a new try block

---

jadx-core/src/main/java/jadx/core/dex/visitors/regions/RegionMaker.java
jadx-core/src/test/java/jadx/tests/integration/loops/TestSynchronizedInEndlessLoop.java
jadx-core/src/test/java/jadx/tests/integration/synchronize/TestSynchronized5.java
jadx-core/src/test/smali/synchronize/TestSynchronized5.smali

This issue appears to come from a difference in understanding of what a synchronized block exit is between `traverseMonitorExitsCross` and the later multi-exit handling in `processMonitorEnter`. 
In this test case, there are two paths out of the first synchronized block: One through a return-void, and one that is more complex and continues into the method. The return-void path is simple enough that it can be pulled into the synchronized block so this *can* be decompiled correctly. However, `traverseMonitorExitsCross` still attempts to find a common cross point between both exits, which fails. 
At that point, no single exit is known (the exit local variable in `processMonitorEnter` is null). In that method, this is not an issue: The fallback handling below recognizes that the return-void …

fix: properly traverse methods with synchronize blocks that have no clear exit

---

jadx-core/src/main/java/jadx/core/dex/visitors/blocksmaker/BlockSplitter.java
jadx-core/src/test/java/jadx/tests/integration/others/TestDeadBlockReferencesStart.java
jadx-core/src/test/smali/others/TestDeadBlockReferencesStart.smali

The old code would ignore the entry block for the first pass of dead code removal but would still remove that block if it was referenced by another dead block, because the entry block has no predecessors.
This patch solves the immediate problem, but I'm not convinced by this approach to dead code elimination. I'm not sure it works reliably for complicated dead code structures. Maybe a tracing GC algorithm would be better? Tracing all the blocks that *are* reachable from the entry node instead of trying to determine which blocks are not. This should be possible in O(n).

fix: do not remove method start block when it is referenced from dead code

---

jadx-core/src/main/java/jadx/core/dex/visitors/InlineMethods.java
jadx-core/src/test/java/jadx/tests/integration/invoke/TestCastInOverloadedAccessor.java

`replaceInsn` copies the attributes from the replaced instruction to the new instruction. This included the `METHOD_DETAILS` attribute. For synthetic accessor methods used for accessing private methods of outer classes, this gives an invoke node that calls the outer method but has a `METHOD_DETAILS` attribute for the synthetic accessor method.
Because of this dissonance, overload processing further downstream would use the method details for the synthetic accessor to process overloads of the normal outer class method. The synthetic accessor includes an additional leading argument: the `Outer.this` argument. In overload processing, this argument would be resolved when it shouldn't be, leading to a cast to the outer class type being inserted for the first argument (i.e. the casts appear one …

fix: preserve original method details in inlined invocation

---

jadx-core/src/main/java/jadx/core/dex/visitors/EnumVisitor.java
jadx-core/src/main/java/jadx/core/dex/visitors/ReSugarCode.java
jadx-core/src/test/java/jadx/tests/integration/enums/TestEnumWithConstInlining.java

To properly decompile enums, the $VALUES initializer must be a filled-array instruction. To create a filled-array instruction, `ReSugarCode` needs a constant array length. Because of constant inlining, this constant array length can be replaced by an sget if the enum is large (>100 elements). Before this patch, this would break filled-array resugaring and thus enum decompilation.

fix: properly transform array creation with constant field length to filled-array

---

jadx-gui/src/main/java/jadx/gui/utils/search/CodeIndex.java

fix: prevent NullPointerException and ConcurrentModificationException when renaming something
Unfortunately even after this fix renaming still doesn't work for me (tried to rename a method of an Interface). With this fix no error is shown, just the renaming does not happen.

Renaming causes various concurrency issues

---

jadx-gui/src/main/java/jadx/gui/ui/JPackagePopupMenu.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/RenameAction.java

If DeobfuscationForceSave settings is enabled the RenameDialog shows a dialog and asks the user to change this setting. 
If the user denies the change the rename dialog is still shown, but without title and any control.

fix: do not show empty RenameDialog

---

jadx-core/src/main/java/jadx/core/dex/instructions/FillArrayData.java
jadx-plugins/jadx-dex-input/src/main/java/jadx/plugins/input/dex/insns/DexInsnFormat.java

the case is at the end of method code item,Insert some fill_array_data_payload instructions with elemSize of 0 at the end of the method.
such as:
The left is before optimization, the right is after optimization
and the smali is:

fix: elemSize=0 fill_array_data_payload insn obfuscation

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/JNodeMenuAction.java

Can not select "Find Usage" and "Go to declaration" in context menu after I upgrade to macOS 11.1
I also tried many versions of java, but none of them works.
Then I look into the source code. Seems that [`codeArea.getMousePosition()`](https://github.com/skylot/jadx/blob/7f8d03d1927b95565938a4e2089f4cbed3417979/jadx-gui/src/main/java/jadx/gui/ui/codearea/JNodeMenuAction.java#L39) failed to retrieve the position.
Related issue: #1052

fix(gui): codearea popup menu always disabled in macos (#1052)

---

jadx-core/src/main/java/jadx/core/utils/StringUtils.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/ui/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/HtmlPanel.java
jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/AbstractCodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/ClassCodeContentPanel.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/CodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/FindUsageAction.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/GoToDeclarationAction.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/RenameAction.java
jadx-gui/src/main/java/jadx/gui/utils/JumpPosition.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties

#1085 
hello, I added some shortcuts for codeArea 
```
- n for rename
- x for usage search
- d / double clicks for goto declaration
- tab for switching between java and smali
- ctrl + tab for swtching between current tab and the previous one
```
and some improvements
1. a line-wrap toggle for codeArea, when code lines is too long it's handy.
2. record caret position in JumpPosition, so the caret can be set rigth at the node not just the start of the line, e.g. when 
click on a search result the caret goes to the matched place not the line head.

Add shortcuts to TabbedPanel & enhence JumpPosition

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/api/JavaVariable.java
jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/main/java/jadx/core/dex/nodes/MethodNode.java
jadx-core/src/main/java/jadx/core/dex/nodes/VariableNode.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/CodePanel.java

#1099 
fix variable usage and set the caret at the new position of the renamed node.

fix variable usage & caret position after rename

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/AbstractCodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/EditorTheme.java

This PR:
1. Removes hard-coded color value for highlighting symbol(default color looks better)
2. Adds a new color scheme: **druid**
Related but doesn't clo$e #1101

Improve color schemes

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

This PR updates the navigation shortcut keys to:
1. <kbd>ESC</kbd> for Backward navigation
2. <kbd>ALT</kbd> + <kbd>⇨</kbd> for Forward navigation
Relates to #1085

Use common keyboard shortcuts for navigation

---

jadx-gui/src/main/java/jadx/gui/ui/ContentPanel.java
jadx-gui/src/main/java/jadx/gui/ui/TabComponent.java

This PR:
- Changes the TabComponent tabs label to only show RootClass name instead of full Class name. This makes navigation between tabs easy.
- Enables TabToolTip, so use can hover over label to see full Class name (as well as resource path). This helps distinguish tabs with duplicate labels.
Before:
https://user-images.githubusercontent.com/11215000/108618497-e3993980-7444-11eb-968d-b7cb4b710fe4.mp4
After:
https://user-images.githubusercontent.com/11215000/108618503-ea27b100-7444-11eb-8d53-a6e69066bfd7.mp4
- Removes the top padding from tab title.
Before:
After:
Closes #1120

Compact TabComponent labels and TabToolTip

---

jadx-gui/src/main/java/jadx/gui/ui/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/SearchDialog.java
jadx-gui/src/main/java/jadx/gui/utils/layout/WrapLayout.java
jadx-gui/src/main/java/jadx/gui/utils/search/SearchSettings.java
jadx-gui/src/main/java/jadx/gui/utils/search/TextSearchIndex.java

When opening the search dialog for the first time the layout was a bit strange, it seems the WrapLayout was reserving space for placing the two search option boxes stacked vertically, but later redecided and placed them horizontally but keeping the vertical space. 
This was may be related to the fact that the target window size was restored after creating all components and additionally an fixed intermediate window size was set. Seems that this confused the Java layouting engines.
Additionally I modified the search dialog to show a red background color in case an invalid regex was entered.

Small search dialog optimizations

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

This fixes an issue in invalid XML. Example of such invalid XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:⺲="" xmlns:android="http://schemas.android.com/apk/res/android"
```
I added validation for empty NS URLs + autogeneration new names for invalid ones

Fix issue in invalid XML NS names

---

jadx-gui/src/main/java/jadx/gui/ui/ADBDialog.java

Recently, I found a mistake that I had made in all my code.
I had always thought that the `continue` (in code below) will go to the `do` statement and start a new round, but nope, according to the official Java documentation
> The continue statement ... skips to the end of the innermost loop's body and evaluates the boolean expression that controls the loop.
So turns out the `continue` goes to the `while (false)`  instead of  `do`. 
```java
do {
if (loop())
continue;
} while (false);
```
I am very sorry for wrote such code to Jadx.

fix a minor bug in while loop

---

jadx-core/src/main/java/jadx/core/Consts.java
jadx-core/src/main/java/jadx/core/codegen/AnnotationGen.java
jadx-core/src/main/java/jadx/core/dex/visitors/OverrideMethodVisitor.java
jadx-core/src/test/java/jadx/tests/integration/others/TestExplicitOverride.java
jadx-core/src/test/smali/others/TestExplicitOverride.smali

The first commit prevents duplicated override annotations for explicit override annotations. The second is a minor optimization: skip override detection for private methods.
This pull request is a fix for #1188

Prevent duplicated Override-annotations + minor optimization

---

jadx-gui/src/main/java/jadx/gui/ui/QuarkDialog.java

This PR refers to [#1119](https://github.com/skylot/jadx/issues/1119).
Hi, sorry for taking so long to fix this.
We (me, @18z, @krnick) have implemented some features:
- **Quark installation in Jadx**:
- A feature that allows users to install Quark-Engine in Jadx with `pip3` (also available on Windows)
- **Error/warning dialog**:
- A feature that pops up the error/warning dialog when Quark was (or maybe will) not work correctly
- **Improvement of progress bar**:
- Implement the progress bar of Quark to `mainWindow`
Changes in this PR:
- **Quark installation in Jadx**:
- Add pip3 and Quark installed check
- Add function to create virtualenv
- Add quark install process
- Add quark rules update process
- **Error/warning dialog**:
- Add a feature that pops up an error dialog for each …

Improvements of Quark integration

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

Reversed XML attribute name decoding priority as discussed in #1208
I looked at different binary XML files and they look consistent, there it seems that reversing the XML attribute decoding priority does not have a negative effect.

reverse XML attribute name decoding priority

---

jadx-core/src/main/java/jadx/core/codegen/ClassGen.java
jadx-core/src/main/java/jadx/core/utils/CodeGenUtils.java
jadx-core/src/test/java/jadx/tests/integration/debuginfo/TestLineNumbers2.java
jadx-core/src/test/java/jadx/tests/integration/loops/TestArrayForEachNegative.java
jadx-gui/src/main/java/jadx/gui/treemodel/JNode.java
jadx-gui/src/main/java/jadx/gui/treemodel/JRoot.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java

1. If multiple files are loaded in Jadx their file paths are now shown as tooltip on the JRoot node
2. Decompiled classes get a comment from which dex files they have been loaded from. This is useful if the APK files contains dex files in non-standard locations (e.g. in assets or other places).
For 2. I also tried to include the APK source file name in the comment in case multiple files are loaded, but it seems that Jadx does not store this information at least I wasn't able to identify how to access this information.  I assume this would require some bigger changes to `DexFileLoader` to carry the original source file information through all the different loader methods to save it in the end in `DexClassData` .

Small improvements (tooltip, dex source file)

---

jadx-core/build.gradle

[aapt2-proto](https://mvnrepository.com/artifact/com.android.tools.build/aapt2-proto/4.2.1-7147631) depends on protobuf-java `3.10.0` which is [broken](https://github.com/protocolbuffers/protobuf/issues/6718) in Java-7 (Android only). This PR fixes the issue by updating proto-buf to 3.11.4

Force protobuf version to prevent Java-7 issue

---

jadx-core/src/main/java/jadx/core/deobf/DeobfPresets.java
jadx-core/src/main/java/jadx/core/dex/visitors/rename/RenameVisitor.java

As I suggested in #1274, the commit will output a jobf file when decompiling to Java.
I'm not sure if it should be on by default because there doesn't seem to be a way to disable it except of passing `/dev/null` as the deobfuscation name but I guess this is the same problem with the deobfuscation feature. What do you think?

Save jobf when decompiling to Java through the cli

---

jadx-gui/src/main/java/jadx/gui/utils/search/ResourceIndex.java

According to the preferences page the resource size index limit is specified in MB but in code it was size * 10KB instead.

fix: configured resource indexing size limit is now correctly considered

---

jadx-core/src/main/java/jadx/core/xmlgen/entry/ValuesParser.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties

I noticed to minor problems:
1. Hexadecimal integers e.g. in AndrdoirManifest.xml were correctly decoded as hex values but the `0x`prefix was missing.
2. The warning about unprotected entries in APK signature only applies to v1 signatures. EN + DE text updated accordingly. Not sure how to handle this for KR and CN languages.

Minor fixes XML decoding and APK signature description

---

jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkReportData.java
jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkReportPanel.java

Please refer to #1289
This PR aims to:
1. make the parsing logic compatible with both versions of Quark reports.
2. show the additional information defined in the old format if possible.
Tested with Quark-Engine v21.8.1, v21.10.2, and v21.11.*.

Update the report parsing in Quark integration

---

jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

On a large APK I had the problem that AndroidManifest.xml generation took ~1 minute or more because the method to search for class references loops over all classes every time a potential reference is found in the XML. 
Instead I added a cache (on-demand initialization) so that we only have to loop one time over all classes now. To reflect changes the cache is deleted after each parse call. 
Cache handling is not thread safe as in my tests it seems like resource decoding is not done multi-threaded.

XML decoding speed enhancement

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

This PR fixes the issue of `nav.forward` shortcut not working on macOS.
closes #1297

fix: forward navigation shortcut on macOS

---

jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/utils/RelativePathTypeAdapter.java

Additionally the save as dialog now suggests a file name for the jadx project file if only one file is loaded.

chore: use relative file paths in .jadx project file (#1312)

---

jadx-gui/src/main/java/jadx/gui/device/debugger/DbgUtils.java

Code works same prior to modification. The while loop ensures all instances of the **<action>** tag are processed. I've added an additional _lastIndexOf_ check for **<activity-alias>** tags. The activity-alias tag gets the _targetActivity_ attribute instead of the _name_.

fix(dgb): support multiple main <action> and <activity-alias> tags

---

jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java

Preferences: processing threads spinner initialization fixed so that it allows to select 1 or 2 threads even if Java is unable to determine the maximum number of available processors.

fix: processing threads spinner initialization (#1331)

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/CodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

PR for #1355.
Adds `Copy as frida snippet` option to code area popup.
- Adds correct overload signature to function snippets.
- Adds arguments (with names) as function parameter.
- Tracks which class definition already given to user. ( no duplicate definitions )
- Inserts kinda dummy information logging to function body.
- Inserts $ to inner class names so frida will be happy.

add frida action to copy methods/classes as frida snippets

---

jadx-cli/src/main/java/jadx/cli/LogHelper.java
jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/JadxPluginManager.java

I've had to resort to some print debugging because of a bug that occurred only outside Intellij, I've added a few logs that I think could be useful to others as well.
One thing to note: I don't think I saw the loaded input files message even in debug mode, not sure if it's a bug with the verbose flag

Add log messages in initialization phase

---

jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java
jadx-core/src/test/java/jadx/api/JadxDecompilerTestUtils.java
jadx-core/src/test/java/jadx/tests/api/ExportGradleTest.java
jadx-core/src/test/java/jadx/tests/export/OptionalTargetSdkVersion.java
jadx-core/src/test/manifest/OptionalTargetSdkVersion.xml
jadx-core/src/test/manifest/strings.xml
jadx-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Here is my proposed fix for issue #1367.
Unfortunately JadxDecompiler was not directly mockable to load raw xml files, so I needed some additional code, to mock it without modifying it.
I hope the testing code for gradle exports can be improved and extended when we have more cases.

Fix gradle export if targetSdkVersion is missing (#1367)

---

jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java
jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/utils/CommonFileUtils.java

When loading file(s) into Jadx the title bar only shows "NewProject" which can be confusing with multiple Jadx windows open.
This PR initializes the project name with loaded file names (max 100 chars) to show them in Jadx title.
Implements #1386

chore(gui): Initialize project name with loaded files 

---

jadx-gui/src/main/java/jadx/gui/device/debugger/DebugController.java
jadx-gui/src/main/java/jadx/gui/device/debugger/EventListenerAdapter.java
jadx-gui/src/main/java/jadx/gui/device/debugger/RuntimeType.java
jadx-gui/src/main/java/jadx/gui/device/debugger/SmaliDebugger.java
jadx-gui/src/main/java/jadx/gui/device/debugger/SmaliDebuggerException.java
jadx-gui/src/main/java/jadx/gui/device/debugger/SuspendInfo.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADB.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADBDevice.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADBDeviceInfo.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/ADBDialog.java
jadx-gui/src/main/java/jadx/gui/utils/IOUtils.java

There were some more IO read problems, also the socket handling is better with ry-with-resource.
I also started to refactor the large classes `ADB` and `SmaliDebugger` by extracting some inner classes.

Smali debugger/Adb io read problems, proper socket closing, ... 

---

gradle.properties
jadx-core/src/main/java/jadx/core/codegen/NameGen.java
jadx-core/src/main/java/jadx/core/utils/log/LogUtils.java
jadx-core/src/test/java/jadx/core/utils/log/LogUtilsTest.java
jadx-gui/src/main/java/jadx/gui/device/debugger/DebugController.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADB.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADBDevice.java
jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java
jadx-gui/src/main/java/jadx/gui/settings/data/ProjectData.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/ADBDialog.java
jadx-gui/src/main/java/jadx/gui/ui/panel/IDebugController.java
jadx-gui/src/main/java/jadx/gui/ui/panel/JDebuggerPanel.java
jadx-gui/src/main/java/jadx/gui/utils/IOUtils.java
jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/JadxPluginManager.java

A bunch of minor improvements to:
*  Preferences dialog -> left side got larger and larger (larger than my screen height) while the right side had plenty of space -> moved plugins group to right side and made sure the plugins list is initialized before the first file is loaded.
* Variable naming "getInstance" special handling
* Do not ask for project save if nothing had been changed (e.g. start Jadx do not load a project and directly close it).
* A lot of minor improvements to the debugger especially for error handling and logging for the case where there are problems.

Minor improvements

---

appdata.xml

flatpak doesn't like <code> and <a> tags, so had to remove them

appdata fixes

---

jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java

Looks like a typo or copy/paste problem from: https://github.com/skylot/jadx/commit/0c9e3227d0337dae81a246884f31c2a54e754aa6 _(So, release 1.3.3+)_
Resolves #1432

Fix method mappings being saved as field mappings

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

Ignore resource chunk entries that are located after the resource chunk end (fix for #751).
I tested loading of a few dozen apps into Jadx and the new code part was never triggered except for the Facebook messenger apps. So with a good chance there should be no new problems introduced by this PR.

Fix resource chunk loading (#751)

---

buildSrc/src/main/groovy/jadx-library.gradle

Accoding to Issue: #1438 I created this pull request since the solution is easy.
Currently the gradle task publishToMavenLocal can not be executed:
```
Execution failed for task ':jadx-core:signMavenJavaPublication'.
Cannot perform signing task ':jadx-core:signMavenJavaPublication' because it has no configured signatory
```
-> gradle tries to sign all publishing tasks. But one might not have proper signing keys configured and one should not need signing for local builds.
Thus, I propose skipping signing for local builds according to:
https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing
Using:
```
signing {
required { gradle.taskGraph.hasTask("publish") }
sign publishing.publications.mavenJava
}
```
and thus only sign builds that should be published to the …

Allow unsigned local lib builds ...gradle task: publishToMavenLocal (fixes #1438)

---

jadx-gui/src/main/java/jadx/gui/settings/data/ProjectData.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

fix(gui): NullPointerException on project save

---

jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/core/ProcessClass.java
jadx-core/src/main/java/jadx/core/utils/DecompilerScheduler.java

By default, when a class filter is applied, only the matching files will be saved.
Alternatively, "setIncludeDependencies(true)" can be used to also have them saved.
Fix #1466

feat: Add option to include/exclude dependencies when saving

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

This PR should fix #1476.
After calling `MainWindow.setEditorTheme` once `MainWindow.editorTheme` always should contain a non-null value. 
First call of `setEditorTheme` is done by `loadSettings`. Assuming an exception is thrown before so that `setEditorTheme` is never called also means that initialization of MainWindow fails, so there should be no UI and state of `editorTheme` field is no longer relevant.

fix(gui): editor theme loading and error/fallback handling improved

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java

Frida code snippet: escape class- method and field names to avoid encoding problems in case the names contain special non-ASCII characters.
Discussion about that topic: https://github.com/skylot/jadx/issues/1355#issuecomment-1121977724

Frida code snippet: escape class- method and field names.

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java

Add function parameters logging in Frida code snippet.
For Example, for the following Java method
```java
public String testJadx(Object object, String string, Integer integer) {
return "1";
}
```
The following Frida code will be generated.
```javascript
let MainActivity = Java.use("com.testjadx.MainActivity");
MainActivity["testJadx"].overload('java.lang.Object', 'java.lang.String', 'java.lang.Integer').implementation = function (object, string, integer) {
console.log('testJadx is called' + ', ' + 'object: ' + object + ', ' + 'string: ' + string + ', ' + 'integer: ' + integer);
let ret = this.testJadx(object, string, integer);
console.log('testJadx ret value is ' + ret);
return ret;
};
```
When the method called in the following,
``` java
testJadx("obj", "str", 123);
```
Frida cli print …

feat(gui): add parameters logging in Frida code snippet

---

jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java

Suggested code changes alter current behavior of window saved state restoration to address the following issues:
- window saved bounds not being restored when they extend past screen bounds in any direction;
- divider location of main window's split pane is restored incorrectly when main window state is restored to maximized.

Fix restoration of windows saved state

---

jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkReportData.java
jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkReportNode.java
jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkReportPanel.java

Issues like #1548 are difficult to debug as they are cause by the data returned by Quark. 
I added data validation regarding the returned confidence value. In case this value is not as expected the whole record is printed, which allows a better understanding what went wrong in Quark.

QuarkReport: data validation added and other minor improvements

---

jadx-gui/src/main/java/jadx/gui/utils/JumpManager.java

Upon opening a new file in Jadx `JumpManager` `list` is reset but not `currentPos`. This can end up in an `IndexOutOfBoundsException` if you use the back function as shown in #1576.

fix: IndexOutOfBoundsException in JumpManager (#1576)

---

jadx-gui/src/main/java/jadx/gui/device/protocol/ADB.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADBDevice.java
jadx-gui/src/main/java/jadx/gui/device/protocol/ADBDeviceInfo.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/ADBDialog.java

Fixed a minor problem when a device disconnects and reconnects: in that case the device data can be incomplete and a device with `null` serial was created.
Furthermore I improved `ADBDeviceInfo` class a bit (getter and constructor).

fix: NullPointerException in adb device viewer (#1585)

---

jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java
jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

Fix for #1583. `@null` is now restricted to values that have a data type of `TYPE_REFERENCE`.
Furthermore I restricted the attribute name replacement to `TYPE_INT_DEC` values, in my tests only attributes with that type had a successful replacement, all the other just caused a `NumberFormatException`.
I compared the resources of several apps decompiled by Jadx and by apktool regarding `@null` replacement. Most apps had the same reference counter of `@null` in both decompiled apps. Some apktool decompiled apps had a few references more but I wasn't able to detect where the exact difference was located as the xml files are often named differently and the attributes are created in a different order which makes comparison difficult.
Last but not least I noticed that deobfuscator had a rule for …

XML "@null" decoding

---

jadx-gui/src/main/java/jadx/gui/treemodel/JRoot.java

fix(gui): sort resources by deobfuscated name

---

jadx-core/src/main/java/jadx/core/xmlgen/ParserConstants.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

fixes #1663
Afterwards it is possible to load the provided sample of #1663 without errors, but the loaded resources in jadx-gui are not what I would expect for a 3.5MB resources.arsc file:
Additionally most of the shown xml resource entries have next to no content. Therefore I assume that the current state of this PR is one step towards fixing this issue, but at the moment it seems to be incomplete and I don't yet understand what is the problem (thus the draft state).

core: Implemented parsing RES_TABLE_TYPE_LIBRARY chunks

---

jadx-core/src/main/java/jadx/core/xmlgen/ResourcesSaver.java
jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/utils/ZipSecurity.java

Logging error messages on invalid file-names or path traversal attacks improved
Fixes #750

Logging error messages improved

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java

Don't use `$new` as `callMethodName` for constructors in frida snippets, but `$init`.
Fixes: https://github.com/skylot/jadx/issues/1714

Change callMethodName of constructors in Frida action

---

jadx-gui/src/main/java/jadx/gui/utils/NLS.java
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties

Added Russian language support

Add Russian translation

---

jadx-gui/src/main/java/jadx/gui/ui/panel/LogcatPanel.java

Could be improved by not re-creating UI every time
Quick fix for logcat debug window causing duplicate windows and incorrect displayed content.
#1752

Simple fix to duplicate/overlapping logcat windows.

---

jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java

Issue it fixes -
[feature] close tab keyboard shortcut #1765

added keyboard shortcut ctrl+w to close tab

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java

The implementation for this feature #1772

print the renamed function name in a frida snippet

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java

Currently if you do `jadx --help`, it says the `--deobf-cfg-file-mode` option accepts the value `read-or-save`. 
However, if you give it that option, it instead prints the following error message:
```
java.lang.IllegalArgumentException: 'read-or-save' is unknown, possible values are: read, read-or-save, overwrite, ignore
at jadx.cli.JadxCLIArgs$DeobfuscationMapFileModeConverter.convert(JadxCLIArgs.java:524)
at jadx.cli.JadxCLIArgs$DeobfuscationMapFileModeConverter.convert(JadxCLIArgs.java:516)
at com.beust.jcommander.JCommander.convertValue(JCommander.java:1340)
at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:249)
at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:920)
at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:901 …
```

Make enum CLI arguments match documented format

---

jadx-core/src/main/java/jadx/core/xmlgen/ParserConstants.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

The implementation to parse OVERLAY chunks in resource table. 
Fixes #1748

chore(core): handle RES_TABLE_TYPE_OVERLAY

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

Parsing of sparse RES_TABLE_TYPE_TYPE chunks and parsing of RES_TABLE_TYPE_STAGED_ALIAS chunks implemented
Also overlay chunk parsing corrected (string length). 
fixes #1806 and #1803

Multiple improvements in parsing resources.arsc

---

jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java
jadx-core/src/main/java/jadx/core/xmlgen/ManifestAttributes.java
jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java
jadx-core/src/main/resources/export/build.gradle.tmpl

I tested recompiling with some random simple apps, e.g.
https://apkpure.com/typescript-tutorial/com.cosmiclearn.typescripttutorial
https://apkpure.com/gradle-dependencies-generator/com.androidgradle.app
and just fixed the first resource or gradle issue in each iteration. The first app now fails with a java issue. I used gradle 7.4.2 to take another bug (also reproducible with gradle 7.6). 
For review: Each commit fixes one bug. I used apktool as a reference for the exported resources.
The following issues can now be closed: https://github.com/skylot/jadx/issues/1073 and https://github.com/skylot/jadx/issues/1682
For the next issues a data structure to aggregate infos for gradle build file generation would help, e.g. for a flag to track usage of "android:pathData-Attributes" + …

Fix resource issues

---

jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java
jadx-core/src/test/java/jadx/tests/api/ExportGradleTest.java
jadx-core/src/test/java/jadx/tests/export/IllegalCharsForGradleWrapper.java
jadx-core/src/test/manifest/IllegalCharsForGradleWrapper.xml

Some special chars in the app name can cause conflicts when you try to add a gradle wrapper. In this pull request I filter all invalid chars before generating settings.gradle
Here is an example app containing invalid chars: https://xn--who-becomes-rich--84ns4b8gwbu6jza3u.apk.gold/
- save as gradle project
- run 'gradle wrapper'
```
FAILURE: Build failed with an exception.
* Where:
Settings file 'settings.gradle' line: 2
* What went wrong:
A problem occurred evaluating settings.
> The project name 'Who Becomes Rich?' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/7.6/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Setting …
```

fix: filter invalid chars for gradle wrapper

---

jadx-core/src/main/java/jadx/core/codegen/InsnGen.java
jadx-core/src/test/java/jadx/tests/integration/java8/TestLambdaArgs.java

```java
foo(1, a -> { return a; });
foo(1, a, b -> { return a + b; });
```
```java
foo(1, a -> { return a; });
foo(1, (a, b) -> { return a + b; });
```

fix: add parentheses around multiple lambda arguments

---

jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java
jadx-core/src/test/java/jadx/core/xmlgen/ResXmlGenTest.java

I noticed that single quotes in xml string arrays were not escaped correctly (`&apos;` instead of \\'). 
Decompile this apk and run a gradle build: https://github.com/ds10git/tvbrowserandroid/releases/download/release_0.7.0.8/TV-Browser-v0.7.0.8.apk
The first build error is caused by a `&apos;` in res/values/arrays.xml.
Reference file is:
https://github.com/ds10git/tvbrowserandroid/blob/master/TV-Browser/res/values/strings.xml 
-> `/resources/string-arrray[@name='pref_category_reminder_names_second']`
This PR will fix this issue.
But first I prepared some unit tests for ResXmlGen to prevent regressions. ResXmlGen had a poor coverage before.

Fix xml escaping for string arrays

---

jadx-core/src/main/java/jadx/api/JadxDecompiler.java
jadx-core/src/main/java/jadx/api/TaskBarrier.java
jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java
jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java
jadx-core/src/main/java/jadx/core/export/ExportGradleTask.java
jadx-core/src/main/java/jadx/core/export/GradleInfoStorage.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ResourcesSaver.java
jadx-core/src/main/resources/export/app.build.gradle.tmpl
jadx-core/src/test/java/jadx/tests/api/ExportGradleTest.java
jadx-core/src/test/java/jadx/tests/export/OptionalTargetSdkVersion.java
jadx-core/src/test/java/jadx/tests/export/VectorDrawablesUseSupportLibrary.java
jadx-core/src/test/java/jadx/tests/functional/TemplateFileTest.java
jadx-core/src/test/manifest/MinSdkVersion25.xml

At the moment missing legacy support for vector drawables (https://developer.android.com/studio/write/vector-asset-studio) is one of the top reasons why recompilation fails. In most cases there wouldn't be a problem if the original dependencies were used (e.g. original material design dependency). Since we don't have any dependency info (yet) in jadx, I would like to propose this PR to add "vectorDrawables.useSupportLibrary = true" when it's needed to continue with the build. I identified two cases for api level 21 and  24.
Example 1 (api level 21):
https://github.com/niranjan94/show-java/releases/download/v3.0.5/ShowJava_v3_0_5.apk ( let Jadx decompile itself :-) )
`File was preprocessed as vector drawable support was added in Android 5.0 (API level 21)`
Example 2 (api level 24): …

fix(gradle): add legacy support for vector drawables

---

jadx-plugins/jadx-rename-mappings/src/main/java/jadx/plugins/mappings/save/MappingExporter.java

Not sure how I haven't caught this earlier, the current implementation overwrites new renames with the old renames from the imported mapping tree. The fix is to copy the old mappings first, and apply the new renames afterwards.

Fix mapping export

---

jadx-core/src/main/resources/export/build.gradle.tmpl

jcenter is deprecated, we can use mavenCentral as one of the default maven repo.

Replace jcenter with mavenCentral

---

jadx-core/src/main/java/jadx/api/plugins/gui/JadxGuiContext.java
jadx-gui/src/main/java/jadx/gui/plugins/context/GuiPluginContext.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/CodeArea.java
jadx-plugins/jadx-script/examples/scripts/gui/bookmark.jadx.kts
jadx-plugins/jadx-script/examples/scripts/gui/caret_mouse.jadx.kts
jadx-plugins/jadx-script/jadx-script-runtime/src/main/kotlin/jadx/plugins/script/runtime/data/Gui.kt

This fixes the last bullet of #1832 by providing the following two features:
* jump to a `ICodeNodeRef` by exposing `jadx.gui.open`.   
The implementation is a simple wrapper over `mainWindow.tabbedPane.codeJump`. It uses `JNodeCache` to cache the `JNode`s created.
* Expose access to the enclosing node for actions, by adding `jadx.gui.(enclosing)?NodeUnder(Caret|mouse)`.   
It is useful for scripts that operates on methods (like Graffiti), as it allows the user to activate the action anywhere inside the function, not only on the function name.
In addition, I've added two sample scripts:
* `gui/caret_mouse.jadx.kts` - Shows the return value of `jadx.gui.(enclosing)?NodeUnder(Caret|mouse)`
* `gui/bookmark.jadx.kts` - Shows the usefulness of `jadx.gui.open` by implementing a single bookmark …

Access node under caret/mouse and jump

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLStrings.java
jadx-core/src/main/java/jadx/core/xmlgen/CommonBinaryParser.java
jadx-core/src/main/java/jadx/core/xmlgen/IResParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ResProtoParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java
jadx-core/src/main/java/jadx/core/xmlgen/entry/ValuesParser.java
jadx-core/src/test/java/jadx/core/xmlgen/ResXmlGenTest.java

Fix #1926.
Works well enough on all the APKs available locally to me (malicious or not), including the sample provided in the referenced issue.
BTW, this sample [AndroidManifest.xml.zip](https://github.com/skylot/jadx/files/11844183/AndroidManifest.xml.zip) uses another technique (an extremely large Unicode string in the place of namespace identifier, where Android doesn't care) to try to crash JADX, any idea on how we could defend against this?

Parse strings only when they are referenced

---

jadx-core/src/main/resources/export/app.build.gradle.tmpl

I changed my mind about implementing buildConfigFields to resolve BuildConfig conflicts (#1847):
```gradle
buildConfigField('Runnable', 'BACKGROUND_THREAD', 'new Runnable() { /* put all your code here */ public void run() { /* insert code with decompilation issues here */ }}')
```
This would create too many new problems. Here is a simple fix to resolve this issue. This setting will be the default in newer AGP versions anyway.

fix(gradle): avoid BuildConfig conflict (#1847)

---

jadx-core/src/main/java/jadx/core/xmlgen/ResXmlGen.java
jadx-core/src/main/java/jadx/core/xmlgen/StringFormattedCheck.java
jadx-core/src/test/java/jadx/core/xmlgen/ResXmlGenTest.java

There is an error message in some cases when a percent sign (%) appears in a resources xml inside a string. The error message is e.g.:
`/app/src/main/res/values/strings.xml:143:4: Multiple substitutions specified in non-positional format of string resource string/certificate_person_details_card_expiration. Did you mean to add the formatted="false" attribute?`
Export this app to gradle and run a build: https://github.com/corona-warn-app/cwa-app-android / https://m.apkpure.com/de/corona-warn-app/de.rki.coronawarnapp
The problem is causes by strings like:
https://github.com/corona-warn-app/cwa-app-android/blob/d98f9c20c595ca5dc877f87f032b47d8b8175a79/Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml#L34
Unlike the devs of SAP jadx does not place quotes …

fix(res): support formatted=false for strings

---

jadx-gui/src/main/java/jadx/gui/plugins/quark/QuarkManager.java

When executing Quark engine output to stdout is redirected to Jadx log, but output to stderr is ignored. 
This patch also redirects output of stderr to Jadx log.
Fix #1955

Also display Quark stderr output in Jadx log

---

jadx-plugins/jadx-script/examples/build.gradle.kts
jadx-plugins/jadx-script/examples/context/Stubs.kt
jadx-plugins/jadx-script/jadx-script-ide/build.gradle.kts
jadx-plugins/jadx-script/jadx-script-plugin/build.gradle.kts
jadx-plugins/jadx-script/jadx-script-runtime/build.gradle.kts
jadx-plugins/jadx-script/jadx-script-runtime/src/main/kotlin/jadx/plugins/script/runtime/JadxScriptTemplate.kt
jadx-plugins/jadx-script/jadx-script-runtime/src/main/kotlin/jadx/plugins/script/runtime/ScriptRuntime.kt

Hi, I created a PR to upgrade kotlin-logging to v5, hope you will be open to accept it. I am the lib maintainer and since this is a breaking change and pact is pretty popular I thought to assist with the upgrade.
Notable changes:
- replace `import mu.` with `import io.github.oshai.kotlinlogging.`
- replace dependency `'io.github.microutils:kotlin-logging-jvm:3.0.5'` to  `io.github.oshai:kotlin-logging-jvm:5.0.1`.

upgrade to kotlin-logging 5

---

jadx-core/src/test/java/jadx/core/xmlgen/ResXmlGenTest.java

The ResXmlGenTest always failed on Windows because of paths using backslash instead of slash and generated XML content containing \r\n but only \n was expected.

fix(core): fix ResXmlGenTest fails on Windows

---

jadx-core/src/main/java/jadx/core/utils/android/AndroidManifestParser.java

After refactoring code in pr #1971, forgot to add a check to ensure AndroidManifest.xml is found before proceeding to look for main activity, which causes a confusing NullPointerException to be thrown.

Fix exception when AndroidManifest.xml is not found in go to main activity action

---

jadx-core/src/main/java/jadx/api/plugins/utils/ZipSecurity.java

exclude ZIP entries of less than 25MB uncompressed size from ZIP bomb check
See #1570

chore: change ZIP bomb test

---

README.md

Arch package was moved to another repo:
> In the new layout extra would contain all packages that were previously in community
― [Official repositories - ArchWiki (archlinux.org)](https://wiki.archlinux.org/title/official_repositories)
See also:
Alternative badge that wouldn't have been broken by this change: ![](https://repology.org/badge/version-for-repo/arch/jadx.svg?header=), from https://repology.org/project/jadx/badges

docs: Update badge

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableParser.java

While implementing the changes of https://github.com/skylot/jadx/pull/1807 in a different project I noticed that in Jadx offset calculation for sparse entries was wrong but without effect as the offset was never used (Jadx assumes all entries can be read correctly ordered right after another in the stream).
This PR corrects the offset calculation and adds additional offset checks.

chore: add resource entry offset check

---

jadx-plugins/jadx-kotlin-metadata/src/main/kotlin/jadx/plugins/kotlin/metadata/pass/KotlinMetadataDecompilePass.kt

Steps to reproduce: 
* Open Jadx GUI (latest git), verify that the option [Plugins -> Kotlin Metadata -> rename fields using toString] is enabled
* Open https://github.com/niranjan94/show-java/releases/download/v3.0.5/ShowJava_v3_0_5.apk (and decompile Jadx itself)
* Navigate in structure tree to package "kotlin.jvm.internal": All class names in that package are valid
* Export sources as gradle project -> now there are two empty items in package "kotlin.jvm.internal"
* Show source code for both items: The class name is " " in both cases and an invalid file "app/src/main/java/kotlin/jvm/internal/ .java" was created.
This PR fixes this issue with a check for valid identifiers before rename. An working alternate fix would be using BetterName, since it includes the valid identifier check, but …

Kotlin toString renamer produces illegal filenames and may override files during export

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/XposedAction.java

fix: Resolved an issue with incorrectly generated xposedMethodSnippet when the parameter type is generic.
add: Introduced xposedGenerateFieldSnippet.
[Main.class.zip](https://github.com/skylot/jadx/files/13464744/Main.class.zip)

fix and add

---

jadx-core/src/main/java/jadx/core/export/ExportGradleTask.java
jadx-core/src/main/java/jadx/core/utils/android/AndroidManifestParser.java

When I try to export this APK (https://python-helper.apk.gold/) as gradle project, I'm getting the same exception like in https://github.com/skylot/jadx/issues/2044 , https://github.com/skylot/jadx/issues/1920 and https://github.com/skylot/jadx/issues/1918
```
java.lang.IllegalStateException
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at jadx.core.export.ExportGradleTask.lambda$run$3(ExportGradleTask.java:58)
at java.base/java.util.Optional.orElseGet(Optional.java:364)
at jadx.core.export.ExportGradleTask.run(ExportGradleTask.java:55)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833) …
```

fix: gradle export for APKs without strings.xml

---

jadx-plugins/jadx-dex-input/src/main/java/jadx/plugins/input/dex/insns/DexInsnFormat.java

When I try to decompile framework.jar (from /system/framework/framework.jar) the following exception occurs
```
ERROR: [5053] IndexOutOfBoundsException in pass: SSATransform in method: android.os.BatteryStats.dumpCheckinLocked(android.content.Context, java.io.PrintWriter, int, int, boolean):void, file: classes2.dex
java.lang.IndexOutOfBoundsException: bitIndex < 0: -80
at java.base/java.util.BitSet.get(BitSet.java:626)
at jadx.core.dex.visitors.ssa.LiveVarAnalysis.fillBasicBlockInfo(LiveVarAnalysis.java:65)
at jadx.core.dex.visitors.ssa.LiveVarAnalysis.runAnalysis(LiveVarAnalysis.java:36)
at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:55)
at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:41)
at …
```

Fixing IndexOutOfBoundsException with negative register index

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/CodePanel.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/SearchBar.java

Before, the search bar would toggle when using the key binding to trigger it (Ctrl + f), which was quite annoying. Now, it replicates IntelliJ's search bar behaviour.
1.1. If the user has selected text, use that as the search text
1.2. Otherwise, use the previous search text (or empty if none)
2. Select all text in the search bar and give it focus

feat: improve search bar behavior when using key bindings

---

jadx-gui/src/main/java/jadx/gui/ui/dialog/RenameDialog.java

This is an attempt to fix the issues that sometimes arise when renaming functions or variables using the "n" shortcut as stated in issue #1440.
The reasoning behind the change: The instance creation of the RenameDialog was somehow affecting the UI thread and not allowing for the key release event to be dispatched. By running everything inside the invokeLater block, this might get fixed as it will execute after all previous tasks are finished. We now also only show the dialog after EVERYTHING is set up, not before.
Only time will tell if this is fixed, but I have not been able to trigger the issue after this change.

fix: attempt to improve field rename issues with "n" shortcut

---

jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockProcessor.java

The method `removeUnreachableBlocks` was iterating through all the methods basic blocks but only keeping the last result found (in `toRemove`).
This will create an error later when the method `checkForUnreachableBlocks` is called.
Therefore, the fix is to use only one instance of the object `toRemove` and keep all the information there.

Fixing removeUnreachable not searching in all blocks

---

jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockProcessor.java
jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockSplitter.java
jadx-core/src/test/smali/conditions/TestTernary4.smali

The counting of removed blocks and removed instructions is not in the right order in `removeUnreachableBlocks`.
`detachBlock` method will zero the instructions of a block before it is analyzed by the code and no warning of the method can be done.
The fix is to reverse the order

Fixing wrong order in removeUnreachableBlocks

---

README.md
jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

Hey! 
I created an option to disable printing XML attributes on new lines for CLI because it creates a lot of problems when parsing/displaying it automatically

Disable XML pretty print

---

README.md

Noticed README had an SVG that is no longer available.
Tried to find a Shields.io workflow that showed ALL build workflows, but looks like I can only pick one.
Another alternative is to simply upload the SVG again, but looking at old commits, I couldn't find any actual file.

Update Build Status shield in README

---

jadx-gui/src/main/java/jadx/gui/ui/TabComponent.java

Hello! Changed `MouseAdapter` callback from `mouseClicked` to `mousePressed`. Reasons:
1. `MouseEvent.MOUSE_CLICKED` is only sent when there is no movement between press and release events, not even a single pixel. Maybe my mouse is too sensitive, but it is challenging to close or select a tab without significally slowing down the mouse or fully stopping it.
2. `BasicTabbedPaneUI.java` itself handles tab selecting within `mousePressed` (line 2611). As a result, the behavior differs when clicking at the tab's center compared (our handler) to clicking at its edges (parent's handler).

Detecting tab click with mousePressed instead of mouseClicked.

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

- download https://apkpure.net/python-documentation-guide/com.thiyagaraaj.learnpython/download/3.8
- decompile apk with latest git, export as gradle
- update `com.android.tools.build:gradle:4.2.2` to version 7.4.0 (newer version generates a more detailed error message, otherwise you would not be able to find the cause)
- add a gradle 7.5 wrapper
- rebuild:
```
./gradlew assembleDebug
> Task :app:processDebugMainManifest
package="com.thiyagaraaj.learnpython" found in source AndroidManifest.xml: app/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: …
```

fix(res): add missing namespace declarations

---

jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockExceptionHandler.java

In a comment to PR https://github.com/skylot/jadx/pull/2086 I tried to report a NPE in some cases, but I wasn't able to provide a stable plain java test case. Now I have an apk with the same issue.
- download https://apkpure.net/python-documentation-guide/com.thiyagaraaj.learnpython/download/3.8
- decompile the method `android.support.v4.graphics.TypefaceCompatUtil.mmap(Context context, CancellationSignal cancellationSignal, Uri uri)` with latest git version:
```
java.lang.NullPointerException: null
at jadx.core.utils.blocks.BlockSet.get(BlockSet.java:24)
at jadx.core.dex.visitors.blocks.BlockExceptionHandler.removeUnusedExcHandlers(BlockExceptionHandler.java:603)
at jadx.core.dex.visitors.blocks.BlockExceptionHandler.process(BlockExceptionHandler.java:72)
at …
```

fix: NPE in unused EcxHandler block removal code (#2086)

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ProtoXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/XmlDeobf.java

Hey!
I noticed that some very obfuscated apps contain duplicated XML attributes in resources. That's why parsing of such XML documents fails.
I didn't check how Android internally handles such cases, but the code in PR only dumps only the first entry

Avoid duplicated XML attrs

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

Jadx generated invalid XML because of missing spaces, e.g.:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="20053842" android:versionName="3.0.609145868" android:compileSdkVersion="34" android:compileSdkVersionCodename="VanillaIceCream" package="com.google.android.apps.adwords" platformBuildVersionCode="34" platformBuildVersionName="VanillaIceCream"xmlns:ns1="http://schemas.android.com/apk/distribution"  ns1:requiredSplitTypes="base__abi"xmlns:ns2="http://schemas.android.com/apk/distribution"  ns2:splitTypes="">
```

Add indents for namespace declarations

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java

1. The elementSize may be larger than the actual size of the element chunk.
2. End namespace chunk size can be any value. also fix issue https://github.com/skylot/jadx/issues/1232 .
[AndroidManifest.zip](https://github.com/skylot/jadx/files/14555279/AndroidManifest.zip)
issue https://github.com/skylot/jadx/issues/1232  APK file.
[com.vmos.pro.apk.zip](https://github.com/skylot/jadx/files/14555312/com.vmos.pro.apk.zip)

fix some manifest decode Error.

---

jadx-gui/src/main/java/jadx/gui/settings/JadxProject.java
jadx-gui/src/main/java/jadx/gui/treemodel/JRoot.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java

Null checks before dereferencing
Fixes #2136

[gui] fix: Handle paths where file name is null

---

jadx-gui/build.gradle.kts

Change default `chdir` launch4j config from `"."` to `""` which disables changes working directory to the jadx-gui.exe program directory.

fix(build): configure launch4j to not change current directory (#2162)

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/HexArea.java

Directly load binary `byte[]` data from (ZIP) file without conversion to String and back.
Fixes #2160

fix(gui): show correct content of binary resources in hex view (#2160)

---

jadx-gui/src/main/java/jadx/gui/ui/filedialog/CustomFileChooser.java
jadx-gui/src/main/java/jadx/gui/ui/filedialog/FileNameMultiExtensionFilter.java

Fixes https://github.com/skylot/jadx/issues/2184
After this commit:
The origional filter uses the last segment split by `.` from file name to match files, so extensions like `.jadx.kts` won't be accepted
```java
public final class FileNameExtensionFilter extends FileFilter {
// ...
public boolean accept(File f) {
if (f != null) {
if (f.isDirectory()) {
return true;
}
// NOTE: we tested implementations using Maps, binary search
// on a sorted list and this implementation. All implementations
// provided roughly the same speed, most likely because of
// overhead associated with java.io.File. Therefor we've stuck
// with the simple lightweight approach.
String fileName = f.getName();
int i = fileName.lastIndexOf('.');
if (i > 0 && i < fileName.length() - 1) {
String desiredExtension = …
```

fix(gui): support filtering files with multiple extensions in file dialog

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLStrings.java

Almost all malicious APKs are now shipped with corrupted manifest. The corruption seep in where the official Android parse is more lenient, particularly the manifest present in these malware has one or more of the following:
- The strings count in the string chunk is almost always invalid. Jadx is immune to this because it correctly ignores it and decode the string on demand, given an index.
- The attributes size of the XML elements is greater than 20 (0x14). I've only seen 24 (0x18) being used, I don't know if Android extended the format (the extra DWORD seems to always be 0).
- Every XML element has an android:tag referencing an invalid string index.
In this patch the attributes size of an XML element is now accounted for.   
This size must be at least 20 (0x14) bytes but can be …

More lenient AXML parsing: allow for non-standard attributes sizes and avoid index exceptions when decoding some strings

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ParserConstants.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableBinaryParser.java

This PR fixes one of the problems that prevents Jadx from loading AndroidManifest.xml included in the sample APK of issue #2182.
Unfortunately I wasn't able to fix all problems so the APK still doesn't load. But may be the changes in this PR will be helpful for other obfuscated APK/AXML files.

More AXML/Manifest parsing improvements

---

jadx-gui/src/main/java/jadx/gui/treemodel/JClass.java
jadx-gui/src/main/java/jadx/gui/treemodel/JResource.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/mode/JCodeMode.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/RenameDialog.java
jadx-gui/src/main/java/jadx/gui/ui/filedialog/FileDialogWrapper.java
jadx-gui/src/main/java/jadx/gui/ui/filedialog/FileOpenMode.java
jadx-gui/src/main/java/jadx/gui/ui/popupmenu/JClassExportType.java
jadx-gui/src/main/java/jadx/gui/ui/popupmenu/JClassPopupMenu.java
jadx-gui/src/main/java/jadx/gui/ui/popupmenu/JPackagePopupMenu.java
jadx-gui/src/main/java/jadx/gui/ui/popupmenu/JResourcePopupMenu.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

Implemented export context menu for following tree nodes
- java class (JClass)
- java package (JPackage)
- resource file (JResource)
- resource folder (JResource)
---
closes #2227
closes #1836

feat(gui): Export resource / class / package

---

jadx-gui/src/main/java/jadx/gui/ui/JadxEventQueue.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/utils/SystemInfo.java
jadx-gui/src/main/java/jadx/gui/utils/UiUtils.java

I had to dig in intellij community source code, as horizontal scrolling works fine there and it also happens to use Java AWT. 
I attached jdb debugger to intellij and put a breakpoint on "MouseWheelEvent", simulated horizontal scroll, and it lead me to the code snippets below :
Here's how it's handled in intellij
https://github.com/JetBrains/intellij-community/blob/654dcd7a253d7f527b1d4d6d17be532a40775b1d/platform/platform-impl/src/com/intellij/ide/IdeEventQueue.kt#L1032-L1049
https://github.com/JetBrains/intellij-community/blob/654dcd7a253d7f527b1d4d6d17be532a40775b1d/platform/util/ui/src/com/intellij/util/ui/StartupUiUtil.kt#L184-L189
I copied these three methods in this commit to a custom `JadxEventQueue`, should I mention the original sources in the code ?
Anyway, horizontal scrolling …

fix(gui): horizontal scrolling in linux

---

jadx-core/src/main/java/jadx/core/dex/instructions/args/SSAVar.java

The result of the `SSAVar#getDetailedVarInfo` method can be used in generated code, so it's important to achieve that the method produces the same result for ssaVars with the same properties.

feat: make detailed var info deterministic

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/AbstractCodeArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/SmaliArea.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/SmaliFoldParser.java

feat(gui): Smali code folding

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableBinaryParser.java

Fixes https://github.com/skylot/jadx/issues/2267

feat(res): support 16-bit entry offsets

---

jadx-cli/src/main/java/jadx/cli/tools/ConvertArscFile.java
jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/api/plugins/utils/ZipSecurity.java
jadx-core/src/main/java/jadx/core/utils/files/ZipFile.java
jadx-plugins/jadx-xapk-input/src/main/java/jadx/plugins/input/xapk/XapkCustomCodeInput.kt
jadx-plugins/jadx-xapk-input/src/main/java/jadx/plugins/input/xapk/XapkUtils.kt

Threat actors are yet again exploiting another lenient-ism in the Android APK loader machinery. I've recently found two APKs whose AndroidManifest.xml ZIP headers was **semi-corrupted in a way that prevents ordinary tools (including Jadx) from correctly processing them**. Android was loading them just fine, though.
The APKs are attached in the ZIP below (password: `infected`) and belongs to two (presumably) very different TAs: one comes from a campaign against Russians using OnlyFans as a bait, the other targets the user of an Italian bank. Thus, I'm inclined to believe this corruptions are intentional and will be used again in the future.
Since APKs are just ZIPs, a little knowledge of the PKZIP format is required. These APKs have the following anomalies:
* The compression method set for …

Adding automatic patching for semi-corrupted APKs

---

jadx-core/src/main/java/jadx/core/dex/visitors/typeinference/TypeCompare.java
jadx-core/src/test/java/jadx/core/dex/visitors/typeinference/PrimitiveConversionsTests.java
jadx-core/src/test/java/jadx/core/dex/visitors/typeinference/TypeCompareTest.java
jadx-core/src/test/java/jadx/tests/integration/others/TestPrimitiveCasts2.java

The PR fixes incorrect primitive-to-primitive conversions:
- `byte` -> `char` - `WIDER` (not `CONFLICT`)
- `short` -> `char` - `WIDER` (not `CONFLICT`)
- `char` -> `byte` - `WIDER` (not `CONFLICT`)
- `char` -> `short` - `WIDER` (not `CONFLICT`)
- `long` -> `float` - `NARROW` (not `WIDER`)
- `float` -> `long` - `WIDER` (not `NARROW`)
- numeric -> `void` - `CONFLICT` (not `NARROW`)
- `void` -> numeric - `CONFLICT` (not `WIDER`)
Fixes https://github.com/skylot/jadx/issues/1620, fixes https://github.com/skylot/jadx/issues/1621, fixes https://github.com/skylot/jadx/issues/1626, indirectly fixes `JadxRuntimeException: Unknown type in literalToString: void`.

fix(core): fix primitive-to-primitive conversions

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/FridaAction.java

When writing hooking codes for a class, write hooking codes for all internal methods for the class.

feat: create hooking code for all internal methods in the class

---

jadx-core/src/main/java/jadx/core/Jadx.java
jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockFinisher.java
jadx-core/src/main/java/jadx/core/dex/visitors/blocks/BlockProcessor.java

Plugins can use .before('BlockFinisher') to edit blocks before they are locked.
If any plugin wants to edit control flow graph after BlockProcessor, blocks are locked. This PR moves `mth.finishBasicBlocks();` line to another visitor called BlockFinisher. So plugins can use .before('BlockFinisher') to edit blocks before they are locked. 
BlockProcessor adds many informations to methodnode, loops, dominators etc.. These are very useful for tracing control flow and editing (for example removing control flow flattening)
Fixes : https://github.com/skylot/jadx/issues/2335

give ability to plugins to edit blocks before locking

---

jadx-core/src/main/java/jadx/core/utils/android/AndroidResourcesUtils.java
jadx-core/src/main/java/jadx/core/xmlgen/ResNameUtils.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableBinaryParser.java
jadx-core/src/test/java/jadx/core/xmlgen/ResNameUtilsTest.java

- Makes sanitized resource names more human-friendly (before: `jadx_deobf_<id>`, after: `<sanitized_name>_<id>`).
- Improves detection of incorrect characters in resource names.
- Fixes an issue where "better name" determination was not performed for styles.
- Fixes an issue where keywords could be used as a field name in the R class.

feat: improve resource names

---

jadx-cli/src/main/java/jadx/cli/tools/ConvertArscFile.java
jadx-core/src/main/java/jadx/core/xmlgen/ParserStream.java
jadx-core/src/main/java/jadx/core/xmlgen/ResTableBinaryParser.java

Some APK resources.arsc seem to use disordered entries, which collides with our approach to read them sequentially from the InputStream. 
As a workaround this PR introduces a BufferedInputStream and mark/reset support for `ParserStream` which allows us to jump back (up to 32k) in stream to read the disordered type chunk entries.
fixes #2343

BufferedInputStream: Allow jumping backwards to an already processed position 

---

jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java
jadx-core/src/test/java/jadx/tests/integration/android/TestResConstReplace3.java

This PR replaces constants in annotation of method arguments. Example:
Having an annotation like 
```java
@Retention(RetentionPolicy.RUNTIME)
public @interface UsesAndroidResource {
int value() default 0;
}
```
this class 
```java
public static class TestCls {
public void test(@UsesAndroidResource(17039370 /* android.R.string.ok */) int i) {
}
}
```
would be decompiled to
```java
public static class TestCls {
public void test(@UsesAndroidResource(R.string.ok) int i) {
}
}
```
I need this fix to generate an issue with AGP > 8.0.0, I'd like to fix later.

feat: replace constants in annotations of method arguments

---

jadx-core/src/main/java/jadx/core/Jadx.java
jadx-core/src/main/java/jadx/core/dex/visitors/gradle/NonFinalResIdsVisitor.java
jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java
jadx-core/src/main/java/jadx/core/export/GradleInfoStorage.java
jadx-core/src/test/java/jadx/tests/api/ExportGradleTest.java
jadx-core/src/test/java/jadx/tests/export/TestNonFinalResIds.java

The android gradle plugin for jadx gradle export can't be updated to newer versions > 8.0.0 due to several issues. One issue e.g. is a compiler error when android resource identifiers are uses as constant expressions.
Example:
Decompile an app with like this, export sources to gradle, update AGP version manually (> 8.0.0) and recompile it:
```java
package` jadx.app.test;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
@Retention(RetentionPolicy.RUNTIME)
public @interface RequiresFinalResId {
int value() default android.R.string.ok;
}
```
```java
package jadx.app.test;
import android.app.Activity;
@RequiresFinalResId(value=R.string.app_name) // <-- error: constant expression required
public class MainActivity extends Activity { …
```

gradle: handle non-final res ids for AGP >8.0.0

---

jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java

inner class name format can be `Class1$InnerClass1`. but it can also be `Class1$method1$InnerClass1` ([example](https://github.com/skylot/jadx/blob/master/jadx-core/src/test/smali/inline/TestSyntheticInline3/TestSyntheticInline3%24onCreate%241.smali)). In [ClassInfo.splitAndApplyNames()](https://github.com/skylot/jadx/blob/47f2e516e54be4e91eee1fc56dd260ee634d0cfd/jadx-core/src/main/java/jadx/core/dex/info/ClassInfo.java#L161), only the former situation is considered. 
This pr is trying to cover the latter situation. If the inner class ClassInfo see its parent class as `Class1$method1`, parent classNode will not be found. In this case `resolveParentClass()` will try to split it again, into `Class1` and `method1`, make sure `Class1` exists and contains method `method1`, then set `Class1` as …

fix: inner class parent is wrong when name formatted as Class$method$xxx

---

jadx-core/src/main/java/jadx/core/dex/visitors/ClassModifier.java
jadx-core/src/test/java/jadx/tests/integration/inner/TestAnonymousClass22.java

If option "inline anonymous class" is checked, sometimes the field of the anonymous class is wrongly recoginized as the instance of its parent class, which actually is instance of a random class. This leads to the field being added `CLASS_INSTANCE` type `FieldReplaceAttr` and displayed as `FieldClassName.this` rather than its normal name.
[example dex](https://github.com/user-attachments/files/18104562/classes.dex.zip)
decompiled code: notice that `another` is displayed as `AnotherClass.this`
```java
public class Parent {
public static Parent test(Class<?> cls) {
final AnotherClass another = new AnotherClass();
return new Parent() { // from class: jadxtest.Parent.1
@Override // jadxtest.Parent
public String func() {
return AnotherClass.this.toString();
}
};
}
public String func() {
return …
```

fix: inline anonymous class wrongly handles field as Classname.this

---

jadx-core/src/main/java/jadx/core/dex/nodes/ClassNode.java
jadx-core/src/test/java/jadx/tests/integration/special/TestPackageInfoSupport.java
jadx-core/src/test/smali/special/TestPackageInfoSupport/pkg3.smali

When I filed https://github.com/skylot/jadx/issues/1967 I had only one sample app. With https://apkpure.com/who-becomes-rich/de.sellfisch.android.wwr/download/1.15.1 I found another app with package-infos e.g. `javax.annotation.package-info`. This time a package-info is just an interface, nothing else. I removed some checks to support this case too.

fix: better package-info support

---

README.md
jadx-cli/build.gradle.kts
jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-gui/src/main/java/jadx/gui/ui/filedialog/FileDialogWrapper.java
jadx-plugins/jadx-apkm-input/build.gradle.kts
jadx-plugins/jadx-apkm-input/src/main/java/jadx/plugins/input/apkm/ApkmCustomCodeInput.kt
jadx-plugins/jadx-apkm-input/src/main/java/jadx/plugins/input/apkm/ApkmCustomResourcesLoader.kt
jadx-plugins/jadx-apkm-input/src/main/java/jadx/plugins/input/apkm/ApkmInputPlugin.kt
jadx-plugins/jadx-apkm-input/src/main/java/jadx/plugins/input/apkm/ApkmManifest.kt
jadx-plugins/jadx-apkm-input/src/main/java/jadx/plugins/input/apkm/ApkmUtils.kt
jadx-plugins/jadx-apkm-input/src/main/resources/META-INF/services/jadx.api.plugins.JadxPlugin
settings.gradle.kts

Added .apkm support for files downloaded from APKMirror.
Closes #2368.
:)

feat: Add APKM support

---

jadx-core/src/main/java/jadx/core/dex/visitors/regions/maker/IfRegionMaker.java
jadx-core/src/main/java/jadx/core/utils/BlockUtils.java
jadx-core/src/test/java/jadx/tests/integration/conditions/TestOutBlock.java
jadx-core/src/test/smali/conditions/TestOutBlock.smali

this pr tries to solve the issue #2384 
when checking whether the then/else block should be extracted as out block, 
- firstly use `getPathCross` to get the cross point(outBlock) of the two blocks. if it's not null, the codes will simply compare out block with then/else block.  
- otherwise the code will fall back to the old method `allPathsFromIf`.
Inside the method `getPathCross`: 
- start block itself is also considered as possible cross point now. 
- when building excluded bitset, add `handlerBlock.getId()` instead of `handlerBlock.getDomFrontier()`. this is to fix a test class failure after the changing above. I'm not sure if this will break other cases.
- remove `combinedDF.clear(block.getId());` in the while loop. it seems that this line is trying to remove the current block after …

fix: IfRegionMaker find the wrong outBlock

---

contrib/jadx-gui.desktop

This pull request adds a `.desktop` file for the GUI which can be copied to `/usr/share/application` on Linux to have a desktop entry to start the program using an application launcher/menu instead of starting it via the terminal via `jadx-gui`. I'm not sure if there's a better place for it, I placed it in a newly created `contrib` folder now as that's what most projects do.
This PR is for having a desktop file entry at Void Linux due to https://github.com/void-linux/void-packages/pull/53772#discussion_r1900208774, as we'd like to upstream desktop files and not vendor them ourselves.
If there are suggestions for improvements, feedback is always welcome! Thanks.

chore: add .desktop file for gui

---

contrib/jadx-gui.desktop
jadx-core/src/main/java/jadx/core/utils/files/FileUtils.java
jadx-gui/build.gradle.kts
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/action/ActionModel.java
jadx-gui/src/main/java/jadx/gui/utils/DesktopEntryUtils.java
jadx-gui/src/main/resources/files/jadx-gui.desktop.tmpl
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

This PR is meant to address #1392.  
While it would be ideal if all distros provided JADX and a matching desktop entry, this is unfortunately still not the case several years after the issue was first created. As someone who uses JADX on a distro without one, I know this is a convenience feature I appreciate JetBrains IDEs having and I think JADX could benefit from it too :)
I implemented this feature by adding a new button to the `Help` dropdown menu at the top of the screen which is only visible on systems where desktop files exist (UNIX, except for MacOS). It uses the standardized xdg commands for installing icons and desktop files to hopefully ensure maximum compatibility.  
While working on the PR I noticed several incorrect values in the already provided desktop file that I changed …

feat: add button to install desktop file directly from jadx-gui

---

jadx-core/src/main/java/jadx/core/xmlgen/ResTableBinaryParser.java

The changes introduced in #2344 allow to parser resources that are not ordered.
I forgot to also consider the new behavior in the code that stops reading entries that are located outside of the chunk. 
The old behavior with ordered entries was to stop parsing if we have reached the end of the chunk. Now with unordered entries we can't stop parsing when we reached the end of the chunk because the next entry may have a lower offset and thus may be located again inside the chunk. 
Without this change entries may be ignored even so they are fully valid. In the [sample app](https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-24-24-14-release/whatsapp-messenger-2-24-24-14-android-apk-download/) mentioned in #2343 all 15 entries of `resources.arsc/res/values/bools.xml` are now present …

fix(res): chunk parsing was aborted too early for unordered entries

---

jadx-gui/src/main/java/jadx/gui/treemodel/ApkSignature.java

jadx.gui.treemodel.ApkSignature currently lacks support for v3.1 APK Signature Scheme.
This PR simply adds display of v3.1 signature info that ApkVerifier already verified and saved to the ApkVerifier.Result object.

Simplistic addition of APK Signature Scheme v3.1 signers

---

jadx-gui/src/main/java/jadx/gui/ui/codearea/XposedAction.kt

fixes #2454
The correct argument type as mentioned in the issue is present in `methodNode.methodInfo.argumentsTypes` (the original source was `methodNode.argTypes`). 
`methodNode.methodInfo.argumentsTypes` is also the source where the Frida code snippet gets the used argument types from.

fix(gui): Xposed snippet argument types corrected (#2454)

---

jadx-gui/src/main/java/jadx/gui/settings/TabStateViewAdapter.java
jadx-gui/src/main/java/jadx/gui/settings/data/TabViewState.java
jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/action/ActionModel.java
jadx-gui/src/main/java/jadx/gui/ui/codearea/EditorViewState.java
jadx-gui/src/main/java/jadx/gui/ui/tab/TabsController.java
jadx-gui/src/main/resources/icons/ui/editorPreview.svg

Apply require changes from https://github.com/skylot/jadx/pull/2474#issuecomment-2849374090
Some changes:
<details>
<summary>Problem</summary>
</details>

fix(gui): improved preview tab behaviors

---

jadx-core/src/main/java/jadx/core/xmlgen/BinaryXMLParser.java
jadx-core/src/main/java/jadx/core/xmlgen/ManifestAttributes.java

Currenty xml attribute value decoding not checks attibute namespace. Attribute like `android:style` and `app:style` it is different attributes, but decode function get only name `style` and trying decode and migt return wrong result. This PR fix it, issue #1675

Fix decode xml attributes value

---

jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java
jadx-core/src/main/java/jadx/api/JadxArgs.java
jadx-core/src/main/java/jadx/api/ResourceFile.java
jadx-core/src/main/java/jadx/api/ResourcesLoader.java
jadx-core/src/main/java/jadx/core/deobf/FileTypeDetector.java
jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java
jadx-core/src/main/java/jadx/core/utils/FileSignature.java
jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java
jadx-gui/src/main/java/jadx/gui/settings/ui/JadxSettingsWindow.java
jadx-gui/src/main/resources/i18n/Messages_de_DE.properties
jadx-gui/src/main/resources/i18n/Messages_en_US.properties
jadx-gui/src/main/resources/i18n/Messages_es_ES.properties
jadx-gui/src/main/resources/i18n/Messages_id_ID.properties
jadx-gui/src/main/resources/i18n/Messages_ko_KR.properties
jadx-gui/src/main/resources/i18n/Messages_pt_BR.properties
jadx-gui/src/main/resources/i18n/Messages_ru_RU.properties
jadx-gui/src/main/resources/i18n/Messages_zh_CN.properties
jadx-gui/src/main/resources/i18n/Messages_zh_TW.properties

Currently jadx get resource extension from name. But if names hard obfuscated and don't have extensions. This PRs slove this problem for detect some popular resources used on apk. Also closes #1643 with correct detection of .9.png.
Example apk how to test: https://github.com/skylot/jadx/issues/584

Added feature to use headers for detect resource extensions

---

jadx-commons/jadx-zip/src/main/java/jadx/zip/fallback/FallbackZipParser.java
jadx-commons/jadx-zip/src/main/java/jadx/zip/io/ByteBufferBackedInputStream.java
jadx-commons/jadx-zip/src/main/java/jadx/zip/io/LimitedInputStream.java
jadx-commons/jadx-zip/src/main/java/jadx/zip/parser/JadxZipParser.java
jadx-commons/jadx-zip/src/main/java/jadx/zip/parser/ZipDeflate.java
jadx-commons/jadx-zip/src/main/java/jadx/zip/security/JadxZipSecurity.java
jadx-core/src/main/java/jadx/api/plugins/utils/ZipSecurity.java
jadx-core/src/main/java/jadx/core/xmlgen/ParserStream.java

As mentioned recently there was no direct way of getting an InputStream of a ZIP entry without having to extract the full entry data to a byte array in memory. 
This PR provides a way to directly get an InputStream for compressed and uncompressed data in a ZIP file.
Only in one case the only way of reading everything to memory is still present: when using the FallbackZipParser.

Provide direct InputStream of ZIP entries

---

jadx-gui/src/main/java/jadx/gui/ui/action/FridaAction.java

When generating Frida hooks, the generated scripts use 'let' for the class reference. Since you're typically prototyping different hooks and copy/pasting the hooks into your script, these let statements clash. Using `var` instead of `let` for the class definition fixes this.
Alternatively we could wrap the generated code in a code block, but this var approach makes more sense to me.

Change let to var in Frida script

---

jadx-core/src/main/resources/export/android/app.build.gradle.tmpl

- Extended the existing lint suppression for `ExpiredTargetSdkVersion` to also include `ExpiringTargetSdkVersion`.
- This ensures that both current and near-future target SDK deprecation warnings are suppressed during builds.
- Keeps the project clean from unnecessary lint noise while maintaining control over SDK updates.

Add missing `ExpiringTargetSdkVersion` in #2533

---

jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/AboutDialog.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/dialog/SearchDialog.java
jadx-gui/src/main/java/jadx/gui/ui/tab/TabbedPane.java

A few minor UI tweaks and fixes.
1. Use system menu bar on macOS, there's no reason to make the user to set `apple.laf.useScreenMenuBar` manually in a custom script.
2. Everything else uses sans font so `AboutDialog` should probably do that too.
3. `GetScrollableUnitIncrement` calculates the horizontal unit increment by column size, so horizontal scrolling is way too fast if you have only a few very wide columns. Override this to a sensible value.
4. The result table has some very bad flickering with auto search enabled, I've increased the debounce timer a little without making it feel sluggish.
5. The wrap-around behavior for tab scrolling is very annoying if you have a large list of tabs open. This could be made configurable but no other text editors or web browsers with tabs does this, …

Minor UI fixes

---

jadx-core/src/main/java/jadx/core/dex/visitors/DotGraphVisitor.java

As described in #2588 there is an issue when generating the CFG. This PR fixes that issue by using `Matcher.quoteReplacement()` as suggested in the Java documentation.
I also noticed a bug where there is a missing space between "CFG for" and the function path in the title. I wasn't sure whether I should put that in a separate pull request.
I'm quite new to contributing to OSS, so I apologize if I don't know the proper procedures for all this.

fix: use proper newlines when generating cfg from backup
